// Generated by CoffeeScript 1.6.3
(function() {
  var ClickableText;

  ClickableText = (function() {
    function ClickableText(name, text, index, x, y) {
      this.initialize(name, text, index, x, y);
    }

    ClickableText.prototype = new createjs.Container();

    ClickableText.prototype.Container_initialize = ClickableText.prototype.initialize;

    ClickableText.prototype.initialize = function(name, text, index, x, y) {
      var hit;
      this.Container_initialize();
      this.name = name;
      this.index = index;
      this.x = x;
      this.y = y;
      this.pos = {
        x: x,
        y: y
      };
      this.text = new createjs.Text(text, '16px Arial', '#333333');
      this.width = this.text.getMeasuredWidth();
      this.height = this.text.getMeasuredHeight();
      hit = new createjs.Shape();
      hit.graphics.beginFill('#000').drawRect(-this.width / 2, this.height / 2, this.width * 2, this.height * 2);
      this.text.hitArea = hit;
      this.addChild(this.text);
      return false;
    };

    window.ClickableText = ClickableText;

    return ClickableText;

  })();

}).call(this);
