// Generated by CoffeeScript 1.6.3
(function() {
  var U7A2,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  U7A2 = (function(_super) {
    __extends(U7A2, _super);

    function U7A2() {
      this.repeatSound = __bind(this.repeatSound, this);
      this.nextEvaluation = __bind(this.nextEvaluation, this);
      this.finishEvaluation = __bind(this.finishEvaluation, this);
      this.evaluateAnswer = __bind(this.evaluateAnswer, this);
      this.evaluateDrop = __bind(this.evaluateDrop, this);
      this.initEvaluation = __bind(this.initEvaluation, this);
      var manifest, sounds;
      manifest = [
        {
          id: 'head',
          src: 'pleca1.png'
        }, {
          id: 'inst',
          src: 'inst.png'
        }, {
          id: 'c1',
          src: 'circle1.png'
        }, {
          id: 'c2',
          src: 'circle2.png'
        }, {
          id: 'repeatbtn',
          src: 'repeat-btn.png'
        }, {
          id: 'playagain',
          src: 'play_again.png'
        }, {
          id: 'startgame',
          src: 'start_game.png'
        }, {
          id: 'btnfinished',
          src: 'btn_finished.png'
        }, {
          id: 'btnrepeat',
          src: 'btn_repeat.png'
        }, {
          id: 'pizarra',
          src: 'pizarra.png'
        }, {
          id: 'boydragblebiking',
          src: 'boy/dragble_biking.png'
        }, {
          id: 'boydragblecanoeing',
          src: 'boy/dragble_canoeing.png'
        }, {
          id: 'boydragbleclean',
          src: 'boy/dragble_clean.png'
        }, {
          id: 'boydragblefishing',
          src: 'boy/dragble_fishing.png'
        }, {
          id: 'boydragbleread',
          src: 'boy/dragble_read.png'
        }, {
          id: 'boydragbleriding',
          src: 'boy/dragble_riding.png'
        }, {
          id: 'boypropbaseball',
          src: 'boy/prop_baseball.png'
        }, {
          id: 'boypropbasketball',
          src: 'boy/prop_basketball.png'
        }, {
          id: 'boypropswimming',
          src: 'boy/prop_swimming.png'
        }, {
          id: 'boyproptennis',
          src: 'boy/prop_tennis.png'
        }, {
          id: 'boy',
          src: 'boy/prop_boy.png'
        }, {
          id: 'girldragblecanoeing',
          src: 'girl/dragble_canoeing.png'
        }, {
          id: 'girldragblefishing',
          src: 'girl/dragble_fishing.png'
        }, {
          id: 'girldragblehiking',
          src: 'girl/dragble_hiking.png'
        }, {
          id: 'girldragblesoccer',
          src: 'girl/dragble_soccer.png'
        }, {
          id: 'girldragbleswimming',
          src: 'girl/dragble_swimming.png'
        }, {
          id: 'girldragblevolleyball',
          src: 'girl/dragble_volleyball.png'
        }, {
          id: 'girlpropclean',
          src: 'girl/prop_clean.png'
        }, {
          id: 'girlproprest',
          src: 'girl/prop_rest.png'
        }, {
          id: 'girlpropriding',
          src: 'girl/prop_riding.png'
        }, {
          id: 'girlproptennis',
          src: 'girl/prop_tennis.png'
        }, {
          id: 'girl',
          src: 'girl/prop_girl.png'
        }
      ];
      sounds = [
        {
          src: 'sounds/good.mp3',
          id: 'good'
        }, {
          src: 'sounds/wrong.mp3',
          id: 'wrong'
        }, {
          src: 'sounds/TU2_U7_A2_instructions.mp3',
          id: 'instructions'
        }, {
          src: 'sounds/TU2_U7_A2_schedule1.mp3',
          id: 'sche1'
        }, {
          src: 'sounds/TU2_U7_A2_schedule2.mp3',
          id: 'sche2'
        }
      ];
      this.game = {
        actividades: {
          boy: ['boypropbaseball', 'boydragbleclean', 'boydragbleread', 'boypropbasketball', 'boyproptennis', 'boydragblecanoeing', 'boypropswimming', 'boydragbleriding', 'boydragblebiking', 'boydragblefishing'],
          boydrags: ['boydragbleclean', 'boydragbleread', 'boydragblecanoeing', 'boydragbleriding', 'boydragblebiking', 'boydragblefishing'],
          girl: ['girldragbleswimming', 'girldragblehiking', 'girldragblesoccer', 'girlpropclean', 'girldragblecanoeing', 'girlpropriding', 'girlproprest', 'girldragblevolleyball', 'girldragblefishing', 'girlproptennis'],
          girldrags: ['girldragbleswimming', 'girldragblehiking', 'girldragblesoccer', 'girldragblecanoeing', 'girldragblevolleyball', 'girldragblefishing']
        }
      };
      U7A2.__super__.constructor.call(this, null, manifest, sounds);
    }

    U7A2.prototype.setStage = function() {
      U7A2.__super__.setStage.apply(this, arguments);
      this.actividades = this.game.actividades;
      this.insertBitmap('header', 'head', stageSize.w / 2, 0, 'tc');
      this.insertBitmap('instructions', 'inst', 20, 100);
      this.insertBitmap('btnRepeat', 'btnrepeat', 650, 367);
      this.insertBitmap('btnFinished', 'btnfinished', 650, 414);
      this.addToMain(new Score('score', this.preload.getResult('c1'), this.preload.getResult('c2'), 20, 500, 6, 0));
      return this.setPizarra(1).introEvaluation();
    };

    U7A2.prototype.setPizarra = function(schedule) {
      var a, actividades, board, c, child, drops, i, j, pizarra, _i, _j, _ref, _ref1;
      this.schedule = schedule;
      pizarra = new createjs.Container();
      pizarra.name = 'pizarra';
      pizarra.x = 61;
      pizarra.y = 103;
      board = this.createBitmap('pizarra', 'pizarra', 167, 31);
      if (schedule === 1) {
        child = this.createBitmap('girl', 'girl', 59, 380, 'bl');
        drops = this.actividades.girl;
        this.drags = this.actividades.girldrags;
      } else {
        child = this.createBitmap('boy', 'boy', 59, 380, 'bl');
        drops = this.actividades.boy;
        this.drags = this.actividades.boydrags;
      }
      actividades = new createjs.Container();
      actividades.name = 'actividades';
      actividades.x = 359;
      actividades.y = 113;
      for (i = _i = 0, _ref = drops.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        if (i < 5) {
          a = this.createBitmap(drops[i], drops[i], 0, i * 49, 'tc');
        } else {
          j = i - 5;
          a = this.createBitmap(drops[i], drops[i], 135, j * 49, 'tc');
        }
        a.scaleX = a.scaleY = 40 / a.image.height;
        if (i === 0 || i === 1 || i === 2 || i === 4 || i === 7 || i === 8) {
          a.visible = false;
        }
        this.addToLibrary(a);
        actividades.addChild(a);
      }
      pizarra.addChild(board, child, actividades);
      for (i = _j = 0, _ref1 = this.drags.length - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
        if (i % 2 === 0) {
          c = new Droppable("dr" + this.drags[i], this.preload.getResult(this.drags[i]), i, 100 * i + 50, 440, this.stage, actividades.children);
        } else {
          c = new Droppable("dr" + this.drags[i], this.preload.getResult(this.drags[i]), i, 100 * i + 50, 400, this.stage, actividades.children);
        }
        c.scaleX = c.scaleY = 0.9;
        this.addToLibrary(c);
        pizarra.addChild(c);
      }
      this.addToMain(pizarra);
      return this;
    };

    U7A2.prototype.introEvaluation = function() {
      U7A2.__super__.introEvaluation.apply(this, arguments);
      TweenLite.from(this.library.header, 1, {
        y: -this.library.header.height
      });
      TweenLite.from(this.library.instructions, 1, {
        alpha: 0,
        x: 0,
        delay: 0.5
      });
      TweenLite.from(this.library.btnRepeat, 1, {
        alpha: 0,
        y: this.library.btnRepeat.y - 5,
        delay: 0.5
      });
      TweenLite.from(this.library.btnFinished, 1, {
        alpha: 0,
        y: this.library.btnFinished.y - 5,
        delay: 0.5
      });
      return TweenLite.from(this.library.pizarra, 1, {
        alpha: 0,
        y: this.library.pizarra.y + 20,
        delay: 1,
        onComplete: this.playInstructions,
        onCompleteParams: [this]
      });
    };

    U7A2.prototype.initEvaluation = function(e) {
      var i, _i, _ref;
      U7A2.__super__.initEvaluation.apply(this, arguments);
      for (i = _i = 0, _ref = this.drags.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        this.library["dr" + this.drags[i]].initDragListener();
        this.library["dr" + this.drags[i]].addEventListener('dropped', this.evaluateDrop);
      }
      this.library.btnRepeat.addEventListener('click', this.repeatSound);
      this.library.btnFinished.addEventListener('click', this.evaluateAnswer);
      return createjs.Sound.play("sche" + this.schedule);
    };

    U7A2.prototype.evaluateDrop = function(e) {
      this.answer = e.target;
      this.drop = e.drop;
      if (this.answer.name === ("dr" + this.drop.name)) {
        this.drop.visible = true;
        return this.answer.visible = false;
      } else {
        this.answer.returnToPlace(1, 0.9, 0.9);
        return this.warning();
      }
    };

    U7A2.prototype.evaluateAnswer = function(e) {
      var i, _i, _ref;
      for (i = _i = 0, _ref = this.drags.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        if (this.library[this.drags[i]].visible === true) {
          this.library.score.plusOne();
        }
      }
      return this.finishEvaluation();
    };

    U7A2.prototype.finishEvaluation = function() {
      createjs.Sound.stop();
      return TweenLite.to(this.library.pizarra, 1, {
        alpha: 0,
        y: this.library.pizarra.y + 20,
        onComplete: this.nextEvaluation
      });
    };

    U7A2.prototype.nextEvaluation = function() {
      /*
      		@index++
      		if @index < @answers.length
      			@library['score'].updateCount( @index )
      			@library['characters'].alpha = 1
      			@library['characters'].y = stageSize.h - 180
      			@library['characters'].currentFrame = @answers[@index].id
      			createjs.Sound.play @answers[@index].sound
      			TweenLite.from @library['characters'], 0.5, {alpha: 0, y: @library['characters'].y + 20, ease: Quart.easeOut}
      		else
      */

      return this.finish();
    };

    U7A2.prototype.repeatSound = function() {
      createjs.Sound.stop();
      return createjs.Sound.play("sche" + this.schedule);
    };

    U7A2.prototype.finish = function() {
      TweenLite.to(this.library.btnRepeat, 1, {
        alpha: 0,
        y: this.library.btnRepeat.y - 5
      });
      TweenLite.to(this.library.btnFinished, 1, {
        alpha: 0,
        y: this.library.btnFinished.y - 5
      });
      return U7A2.__super__.finish.apply(this, arguments);
    };

    window.U7A2 = U7A2;

    return U7A2;

  })(Oda);

}).call(this);
