// Generated by CoffeeScript 1.6.3
(function() {
  var DraggableText,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  DraggableText = (function() {
    function DraggableText(name, text, index, x, y) {
      this.blinkAgain = __bind(this.blinkAgain, this);
      this.handleMouseDown = __bind(this.handleMouseDown, this);
      this.onInitEvaluation = __bind(this.onInitEvaluation, this);
      this.initialize(name, text, index, x, y);
    }

    DraggableText.prototype = new createjs.Container();

    DraggableText.prototype.Container_initialize = DraggableText.prototype.initialize;

    DraggableText.prototype.initialize = function(name, text, index, x, y) {
      var hit;
      this.Container_initialize();
      this.name = name;
      this.index = index;
      this.x = x;
      this.y = y;
      this.pos = {
        x: x,
        y: y
      };
      this.text = new createjs.Text(text, '16px Arial', '#333333');
      this.text.textAlign = 'center';
      hit = new createjs.Shape();
      hit.graphics.beginFill('#000').drawRect(0, 0, this.text.getMeasuredWidth(), this.text.getMeasuredHeight());
      this.text.hitArea = hit;
      this.addChild(this.text);
      return false;
    };

    DraggableText.prototype.onInitEvaluation = function() {
      return this.addEventListener('mousedown', this.handleMouseDown);
    };

    DraggableText.prototype.handleMouseDown = function(e) {
      var offset, posX, posY,
        _this = this;
      posX = e.stageX / stageSize.r;
      posY = e.stageY / stageSize.r;
      offset = {
        x: posX - this.x,
        y: posY - this.y
      };
      this.x = posX - offset.x;
      this.y = posY - offset.y;
      e.addEventListener('mousemove', function(ev) {
        posX = ev.stageX / stageSize.r;
        posY = ev.stageY / stageSize.r;
        _this.x = posX - offset.x;
        _this.y = posY - offset.y;
        return false;
      });
      e.addEventListener('mouseup', function(ev) {
        _this.dispatchEvent('drop');
        return false;
      });
      return false;
    };

    DraggableText.prototype.blink = function(state) {
      if (state == null) {
        state = true;
      }
      TweenMax.killTweensOf(this);
      this.alpha = 1;
      if (state) {
        return TweenMax.to(this, 0.2, {
          alpha: .2,
          repeat: -1,
          yoyo: true
        });
      }
    };

    DraggableText.prototype.blinkAgain = function() {
      TweenLite.killTweensOf(this);
      return this.blink(true);
    };

    DraggableText.prototype.returnToPlace = function() {
      return TweenLite.to(this, 0.5, {
        ease: Back.easeOut,
        delay: 0.1,
        x: this.pos.x,
        y: this.pos.y,
        alpha: 1,
        scaleX: 1,
        scaleY: 1
      });
    };

    window.DraggableText = DraggableText;

    return DraggableText;

  })();

}).call(this);
