// Generated by CoffeeScript 1.6.3
(function() {
  var U1A5,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  U1A5 = (function(_super) {
    __extends(U1A5, _super);

    function U1A5() {
      this.repeatSound = __bind(this.repeatSound, this);
      this.nextEvaluation = __bind(this.nextEvaluation, this);
      this.finishEvaluation = __bind(this.finishEvaluation, this);
      this.evaluateAnswer = __bind(this.evaluateAnswer, this);
      this.initEvaluation = __bind(this.initEvaluation, this);
      var manifest, sounds;
      manifest = [
        {
          id: 'head',
          src: 'pleca.png'
        }, {
          id: 'inst',
          src: 'texto_look.png'
        }, {
          id: 'c1',
          src: 'circle1.png'
        }, {
          id: 'c2',
          src: 'circle2.png'
        }, {
          id: 'repeatbtn',
          src: 'repeat-btn.png'
        }, {
          id: 'playagain',
          src: 'play_again.png'
        }, {
          id: 'startgame',
          src: 'start_game.png'
        }, {
          id: 'bg',
          src: 'bg.png'
        }
      ];
      sounds = [
        {
          src: 'sounds/boing.mp3',
          id: 'boing'
        }, {
          src: 'sounds/TU2_U4_A6_instructions.mp3',
          id: 'instructions'
        }
      ];
      this.answers = [];
      this.textos = {
        positions: [
          {
            x: '100',
            y: '182'
          }, {
            x: '100',
            y: '281'
          }, {
            x: '100',
            y: '318'
          }, {
            x: '100',
            y: '355'
          }, {
            x: '100',
            y: '375'
          }, {
            x: '424',
            y: '182'
          }, {
            x: '424',
            y: '233'
          }, {
            x: '424',
            y: '320'
          }, {
            x: '424',
            y: '352'
          }, {
            x: '424',
            y: '285'
          }, {
            x: '424',
            y: '322'
          }, {
            x: '424',
            y: '390'
          }
        ],
        parrafo1: ["It's a beautiful fall day in Lakeville. The         are full", 'of bright red and yellow leaves. There are apples,', 'peaches and pears on the trees. Paul and Megan are ', 'standing next to the        , which is full of clear blue', 'water. They are planting a tree. A cool          blows', 'gently. Megan remembers the Kingdom of Waters.'],
        parrafo2: ['"Things are very different now, aren' + "'" + 't they?" she says', 'to Paul.'],
        parrafo3: ['"A lot of things are different. There' + "'s water now for", 'all the plants and             ," he says.'],
        parrafo4: ['"For us, too," Megan adds.'],
        parrafo5: ['The wind blows again. Paul remembers flying with', 'Amedrah, looking at the lakes and rivers of the', 'Kingdom of Waters. "Too bad Amerah the dragon'],
        parrafo6: ["can't visit us here. I want to fly on his          above", 'Lakeville and see the lake from the air. I bet it looks', 'beautiful!"'],
        parrafo7: ["They take the Magic Rain Book out of Paul's", "               . They look at the book's cover. in the", 'bright              , they see something new and', 'surprising. The little says, "The Kigndom of Waters."', 'Under the title, it says, "Imagine it is your          !"'],
        parrafo8: ['"I have an idea," Megan says. "Let' + "'s imagine that", 'Amedrah the dragon is here with us in our world!"'],
        parrafo9: ['The kids close their          . The wind starts blowing.', 'The kids look up. A purple dragon appears in the', 'clear blue        , Paul and Megan look at each other', 'and smile.'],
        drags: [
          {
            id: 'trees',
            x: '701',
            y: '492'
          }, {
            id: 'lake',
            x: '665',
            y: '547'
          }, {
            id: 'wind',
            x: '731',
            y: '532'
          }, {
            id: 'animals',
            x: '557',
            y: '497'
          }, {
            id: 'back',
            x: '496',
            y: '484'
          }, {
            id: 'backpack',
            x: '595',
            y: '542'
          }, {
            id: 'sunlight',
            x: '574',
            y: '459'
          }, {
            id: 'world',
            x: '659',
            y: '468'
          }, {
            id: 'eyes',
            x: '518',
            y: '533'
          }, {
            id: 'sky',
            x: '634',
            y: '511'
          }
        ]
      };
      U1A5.__super__.constructor.call(this, null, manifest, sounds);
    }

    U1A5.prototype.setStage = function() {
      U1A5.__super__.setStage.apply(this, arguments);
      this.insertBitmap('bg', 'bg', 0, 54);
      this.insertBitmap('header', 'head', stageSize.w / 2, 0, 'tc');
      this.insertBitmap('instructions', 'inst', 20, 100);
      this.addToMain(new Score('score', this.preload.getResult('c1'), this.preload.getResult('c2'), 20, 500, 5, 0));
      return this.setCuento().setDropper().introEvaluation();
    };

    U1A5.prototype.setCuento = function() {
      var i, j, text, _i, _j, _k, _ref;
      text = new createjs.Text('Episode 3', '13px Arial', '#333');
      text.x = 641;
      text.y = 146;
      this.addToMain(text);
      for (i = _i = 1; _i <= 9; i = _i += 1) {
        for (j = _j = 0, _ref = this.textos["parrafo" + i].length; 0 <= _ref ? _j <= _ref : _j >= _ref; j = 0 <= _ref ? ++_j : --_j) {
          text = new createjs.Text(this.textos["parrafo" + i][j], '13px Arial', '#333');
          text.x = this.textos.positions[i - 1].x;
          text.y = this.textos.positions[i - 1].y - (-j * 15);
          this.addToMain(text);
        }
      }
      for (i = _k = 1; _k <= 10; i = ++_k) {
        text = new DraggableText(this.textos.drags[i - 1].id, this.textos.drags[i - 1].id, i, this.textos.drags[i - 1].x, this.textos.drags[i - 1].y);
        this.addToMain(text);
      }
      return this;
    };

    U1A5.prototype.setDropper = function() {
      var dropper, h1, h10, h2, h3, h4, h5, h6, h7, h8, h9;
      dropper = new createjs.Container();
      dropper.x = 0;
      dropper.y = 0;
      dropper.name = 'dropper';
      h1 = new WordContainer('h1', '', '', '#f39234', 323, 184, 30, 13);
      h2 = new WordContainer('h2', '', '', '#f39234', 218, 228, 33, 13);
      h3 = new WordContainer('h3', '', '', '#f39234', 323, 242, 36, 13);
      h4 = new WordContainer('h4', '', '', '#f39234', 202, 335, 47, 13);
      h5 = new WordContainer('h5', '', '', '#f39234', 639, 184, 35, 13);
      h6 = new WordContainer('h6', '', '', '#f39234', 425, 249, 57, 13);
      h7 = new WordContainer('h7', '', '', '#f39234', 459, 264, 53, 13);
      h8 = new WordContainer('h8', '', '', '#f39234', 667, 295, 36, 13);
      h9 = new WordContainer('h9', '', '', '#f39234', 540, 354, 45, 13);
      h10 = new WordContainer('h9', '', '', '#f39234', 482, 384, 30, 13);
      dropper.addChild(h1, h2, h3, h4, h5, h6, h7, h8, h9, h10);
      this.addToLibrary(h1, h2, h3, h4, h5, h6, h7, h8, h9);
      this.addToMain(dropper);
      return this;
    };

    U1A5.prototype.introEvaluation = function() {
      return U1A5.__super__.introEvaluation.apply(this, arguments);
      /*
      		for i in [1..6] by 1
      			@observer.subscribe 'init_evaluation', @library['name'+i].onInitEvaluation
      
      		@library['characters'].currentFrame = @answers[@index].id
      
      		TweenLite.from @library['header'], 1, {y:-@library['header'].height}
      		TweenLite.from @library['instructions'], 1, {alpha :0, x: 0, delay: 0.5}
      		TweenLite.from @library['names'], 1, {alpha: 0, y: @library['names'].y + 50, delay: 1}
      		TweenLite.from @library['dropname'], 1, {alpha: 0, y: @library['dropname'].y + 50, delay: 1}
      		TweenLite.from @library['characters'], 1, {alpha: 0, y: @library['characters'].y + 20, delay: 1.5, onComplete: @playInstructions, onCompleteParams: [@]}
      */

    };

    U1A5.prototype.initEvaluation = function(e) {
      U1A5.__super__.initEvaluation.apply(this, arguments);
      this.library['characters'].currentFrame = this.answers[this.index].id;
      createjs.Sound.play(this.answers[this.index].sound);
      return TweenLite.to(this.library['characters'], 0.5, {
        alpha: 1,
        y: stageSize.h - 180,
        ease: Quart.easeOut
      });
    };

    U1A5.prototype.evaluateAnswer = function(e) {
      var pt;
      this.answer = e.target;
      pt = this.library['dropname'].globalToLocal(this.stage.mouseX, this.stage.mouseY);
      if (this.library['dropname'].hitTest(pt.x, pt.y)) {
        if (this.answer.index === this.answers[this.index].id) {
          this.answer.blink(false);
          return setTimeout(this.finishEvaluation, 1 * 1000);
        } else {
          this.warning();
          return this.answer.returnToPlace();
        }
      } else {
        return this.answer.returnToPlace();
      }
    };

    U1A5.prototype.finishEvaluation = function() {
      TweenLite.to(this.library['characters'], 0.5, {
        alpha: 0,
        y: -200,
        ease: Back.easeOut,
        onComplete: this.nextEvaluation
      });
      return this.answer.returnToPlace();
    };

    U1A5.prototype.nextEvaluation = function() {
      this.index++;
      if (this.index < this.answers.length) {
        this.library['score'].updateCount(this.index);
        this.library['characters'].alpha = 1;
        this.library['characters'].y = stageSize.h - 180;
        this.library['characters'].currentFrame = this.answers[this.index].id;
        createjs.Sound.play(this.answers[this.index].sound);
        return TweenLite.from(this.library['characters'], 0.5, {
          alpha: 0,
          y: this.library['characters'].y + 20,
          ease: Quart.easeOut
        });
      } else {
        return this.finish();
      }
    };

    U1A5.prototype.repeatSound = function() {
      return createjs.Sound.play(this.answers[this.index].sound);
    };

    U1A5.prototype.finish = function() {
      var i, _i, _results;
      U1A5.__super__.finish.apply(this, arguments);
      _results = [];
      for (i = _i = 1; _i <= 6; i = _i += 1) {
        _results.push(this.library['name' + i].blink(false));
      }
      return _results;
    };

    window.U1A5 = U1A5;

    return U1A5;

  })(Oda);

}).call(this);
