// Generated by CoffeeScript 1.6.3
(function() {
  var U4A6,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  U4A6 = (function(_super) {
    __extends(U4A6, _super);

    function U4A6() {
      this.nextEvaluation = __bind(this.nextEvaluation, this);
      this.finishEvaluation = __bind(this.finishEvaluation, this);
      this.evaluateAnswer = __bind(this.evaluateAnswer, this);
      this.setClick = __bind(this.setClick, this);
      this.initEvaluation = __bind(this.initEvaluation, this);
      var manifest, sounds;
      manifest = [
        {
          id: 'head',
          src: 'pleca1.png'
        }, {
          id: 'inst',
          src: 'inst.png'
        }, {
          id: 'c1',
          src: 'circle1.png'
        }, {
          id: 'c2',
          src: 'circle2.png'
        }, {
          id: 'repeatbtn',
          src: 'repeat-btn.png'
        }, {
          id: 'playagain',
          src: 'play_again.png'
        }, {
          id: 'startgame',
          src: 'start_game.png'
        }, {
          id: 'Asiangirl',
          src: 'Asian-girl.png'
        }, {
          id: 'boyhair',
          src: 'boy-hair.png'
        }, {
          id: 'brushtowelsoap',
          src: 'brush-towel-soap.png'
        }, {
          id: 'brushinghisteeth',
          src: 'brushing-his-teeth.png'
        }, {
          id: 'busfullpeople',
          src: 'bus-full-people.png'
        }, {
          id: 'chef',
          src: 'chef.png'
        }, {
          id: 'chopsticks',
          src: 'chopsticks.png'
        }, {
          id: 'cloudyday',
          src: 'cloudy-day.png'
        }, {
          id: 'familyChristmas',
          src: 'family-Christmas.png'
        }, {
          id: 'fullmoon',
          src: 'full-moon.png'
        }, {
          id: 'girlcanoeing',
          src: 'girl-canoeing.png'
        }, {
          id: 'girlhair',
          src: 'girl-hair.png'
        }, {
          id: 'hotday',
          src: 'hot-day.png'
        }, {
          id: 'leaves',
          src: 'leaves.png'
        }, {
          id: 'librarian',
          src: 'librarian.png'
        }, {
          id: 'mapaSB',
          src: 'mapa-SB.png'
        }, {
          id: 'motherchild',
          src: 'mother-child.png'
        }, {
          id: 'necklace',
          src: 'necklace.png'
        }, {
          id: 'USmoney',
          src: 'US-money.png'
        }
      ];
      sounds = [
        {
          src: 'sounds/good.mp3',
          id: 'good'
        }, {
          src: 'sounds/boing.mp3',
          id: 'boing'
        }, {
          src: 'sounds/TU2_U4_A6_instructions.mp3',
          id: 'instructions'
        }, {
          src: 'sounds/wrong.mp3',
          id: 'wrong'
        }
      ];
      this.game = {
        preguntas: [
          {
            tipo: 'texto',
            imagen: 'Asiangirl',
            pregunta: '',
            opcionUno: '',
            opcionDos: '',
            respuesta: ''
          }, {
            tipo: 'texto',
            imagen: 'boyhair',
            pregunta: '',
            opcionUno: '',
            opcionDos: '',
            respuesta: ''
          }, {
            tipo: 'texto',
            imagen: 'brushtowelsoap',
            pregunta: 'What are you packing?',
            opcionUno: 'Soap, a toothbrush, a comb and a towel.',
            opcionDos: 'Soap, a brush, toothpaste and a towel.',
            respuesta: 'Soap, a brush, toothpaste and a towel.'
          }, {
            tipo: 'texto',
            imagen: 'brushinghisteeth',
            pregunta: '',
            opcionUno: '',
            opcionDos: '',
            respuesta: ''
          }, {
            tipo: 'texto',
            imagen: 'busfullpeople',
            pregunta: '',
            opcionUno: '',
            opcionDos: '',
            respuesta: ''
          }, {
            tipo: 'texto',
            imagen: 'chef',
            pregunta: '',
            opcionUno: '',
            opcionDos: '',
            respuesta: ''
          }, {
            tipo: 'texto',
            imagen: 'chopsticks',
            pregunta: '',
            opcionUno: '',
            opcionDos: '',
            respuesta: ''
          }, {
            tipo: 'texto',
            imagen: 'cloudyday',
            pregunta: '',
            opcionUno: '',
            opcionDos: '',
            respuesta: ''
          }, {
            tipo: 'texto',
            imagen: 'familyChristmas',
            pregunta: '',
            opcionUno: '',
            opcionDos: '',
            respuesta: ''
          }, {
            tipo: 'texto',
            imagen: 'fullmoon',
            pregunta: '',
            opcionUno: '',
            opcionDos: '',
            respuesta: ''
          }, {
            tipo: 'texto',
            imagen: 'girlcanoeing',
            pregunta: '',
            opcionUno: '',
            opcionDos: '',
            respuesta: ''
          }, {
            tipo: 'texto',
            imagen: 'girlhair',
            pregunta: '',
            opcionUno: '',
            opcionDos: '',
            respuesta: ''
          }, {
            tipo: 'texto',
            imagen: 'hotday',
            pregunta: '',
            opcionUno: '',
            opcionDos: '',
            respuesta: ''
          }, {
            tipo: 'texto',
            imagen: 'leaves',
            pregunta: '',
            opcionUno: '',
            opcionDos: '',
            respuesta: ''
          }, {
            tipo: 'texto',
            imagen: 'librarian',
            pregunta: '',
            opcionUno: '',
            opcionDos: '',
            respuesta: ''
          }, {
            tipo: 'texto',
            imagen: 'mapaSB',
            pregunta: '',
            opcionUno: '',
            opcionDos: '',
            respuesta: ''
          }, {
            tipo: 'texto',
            imagen: 'motherchild',
            pregunta: '',
            opcionUno: '',
            opcionDos: '',
            respuesta: ''
          }, {
            tipo: 'texto',
            imagen: 'necklace',
            pregunta: '',
            opcionUno: "It's nineteen dollars and fifteen cents.",
            opcionDos: "It's nineteen dollars and fifty cents",
            respuesta: "It's nineteen dollars and fifty cents"
          }, {
            tipo: 'texto',
            imagen: 'USmoney',
            pregunta: '',
            opcionUno: '',
            opcionDos: '',
            respuesta: ''
          }
        ]
      };
      U4A6.__super__.constructor.call(this, null, manifest, sounds);
    }

    U4A6.prototype.setStage = function() {
      U4A6.__super__.setStage.apply(this, arguments);
      this.preguntas = this.shuffleNoRepeat(this.game.preguntas, 16);
      this.insertBitmap('header', 'head', stageSize.w / 2, 0, 'tc');
      this.insertBitmap('instructions', 'inst', 20, 100);
      this.addToMain(new Score('score', this.preload.getResult('c1'), this.preload.getResult('c2'), 20, 500, 16, 0));
      return this.setQuestion(0).introEvaluation();
    };

    U4A6.prototype.setQuestion = function(i) {
      var diagonal, dos, opciones, question, text, total, uno, v;
      question = new createjs.Container();
      question.x = 0;
      question.y = 0;
      question.name = 'question';
      if (this.preguntas[i].tipo === 'texto') {
        v = this.createBitmap(this.preguntas[i].imagen, this.preguntas[i].imagen, stageSize.w / 2, stageSize.h / 2 + 30, 'mc');
        v.scaleX = v.scaleY = 0.5;
        question.addChild(v);
        this.addToLibrary(v);
        text = new createjs.Text(this.preguntas[i].pregunta, '24px Quicksand', '#333');
        text.name = 'titulo';
        text.x = stageSize.w / 2;
        text.y = 140;
        text.textAlign = 'center';
        question.addChild(text);
        this.addToLibrary(text);
        opciones = new createjs.Container();
        uno = new ClickableText(this.preguntas[i].opcionUno, this.preguntas[i].opcionUno, i, 0, 0);
        opciones.addChild(uno);
        this.addToLibrary(uno);
        diagonal = new createjs.Text('/', '16px Quicksand', '#333');
        diagonal.name = 'diagonal';
        diagonal.x = uno.x + uno.width;
        diagonal.y = 0;
        opciones.addChild(diagonal);
        this.addToLibrary(diagonal);
        dos = new ClickableText(this.preguntas[i].opcionDos, this.preguntas[i].opcionDos, i, diagonal.x + 10, 0);
        opciones.addChild(dos);
        this.addToLibrary(dos);
        total = uno.width + dos.width + 20;
        opciones.x = stageSize.w / 2 - total / 2;
        opciones.y = 490;
        question.addChild(opciones);
      }
      this.addToMain(question);
      return this;
    };

    U4A6.prototype.introEvaluation = function() {
      U4A6.__super__.introEvaluation.apply(this, arguments);
      TweenLite.from(this.library['header'], 1, {
        y: -this.library['header'].height
      });
      TweenLite.from(this.library['instructions'], 1, {
        alpha: 0,
        x: 0,
        delay: 0.5
      });
      return TweenLite.from(this.library['question'], 1, {
        alpha: 0,
        y: this.library['question'].y - 20,
        delay: 1,
        onComplete: this.playInstructions,
        onCompleteParams: [this]
      });
    };

    U4A6.prototype.initEvaluation = function(e) {
      U4A6.__super__.initEvaluation.apply(this, arguments);
      return this.setClick(0);
    };

    U4A6.prototype.setClick = function(i) {
      this.library[this.preguntas[i].opcionUno].index = 'opcionUno';
      this.library[this.preguntas[i].opcionDos].index = 'opcionDos';
      this.library[this.preguntas[i].opcionUno].addEventListener('click', this.evaluateAnswer);
      this.library[this.preguntas[i].opcionDos].addEventListener('click', this.evaluateAnswer);
      return this;
    };

    U4A6.prototype.evaluateAnswer = function(e) {
      this.answer = e.target;
      if (this.answer.index === this.preguntas[this.index].respuesta) {
        createjs.Sound.play('good');
        this.library['score'].plusOne();
        return this.finishEvaluation();
      } else {
        return this.warning();
      }
    };

    U4A6.prototype.finishEvaluation = function() {
      if (this.preguntas[this.index].tipo === 'texto') {
        TweenLite.to(this.library[this.preguntas[this.index].opcionUno], 0.5, {
          alpha: 0,
          y: stageSize.h,
          ease: Back.easeOut
        });
        TweenLite.to(this.library[this.preguntas[this.index].opcionDos], 0.5, {
          alpha: 0,
          y: stageSize.h,
          ease: Back.easeOut
        });
        TweenLite.to(this.library['titulo'], 0.5, {
          alpha: 0,
          y: stageSize.h,
          ease: Back.easeOut
        });
        TweenLite.to(this.library['diagonal'], 0.5, {
          alpha: 0,
          y: stageSize.h,
          ease: Back.easeOut
        });
        return TweenLite.to(this.library[this.preguntas[this.index].imagen], 0.5, {
          alpha: 0,
          y: stageSize.h,
          ease: Back.easeOut,
          onComplete: this.nextEvaluation
        });
      } else if (this.preguntas[this.index].tipo === 'imagen') {
        TweenLite.to(this.library['titulo'], 0.5, {
          alpha: 0,
          y: stageSize.h,
          ease: Back.easeOut,
          onComplete: this.nextEvaluation
        });
        TweenLite.to(this.library[this.preguntas[this.index].opcionDos], 0.5, {
          alpha: 0,
          y: stageSize.h,
          ease: Back.easeOut
        });
        return TweenLite.to(this.library[this.preguntas[this.index].opcionUno], 0.5, {
          alpha: 0,
          y: stageSize.h,
          ease: Back.easeOut
        });
      }
    };

    U4A6.prototype.nextEvaluation = function() {
      this.index++;
      if (this.index < this.preguntas.length) {
        return this.setQuestion(this.index).setClick(this.index);
      } else {
        return this.finish();
      }
    };

    U4A6.prototype.finish = function() {
      return U4A6.__super__.finish.apply(this, arguments);
    };

    window.U4A6 = U4A6;

    return U4A6;

  })(Oda);

}).call(this);
