// Generated by CoffeeScript 1.6.3
(function() {
  var U3A4,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  U3A4 = (function(_super) {
    __extends(U3A4, _super);

    function U3A4() {
      this.nextEvaluation = __bind(this.nextEvaluation, this);
      this.finishEvaluation = __bind(this.finishEvaluation, this);
      this.evaluateAnswer3 = __bind(this.evaluateAnswer3, this);
      this.evaluateAnswer2 = __bind(this.evaluateAnswer2, this);
      this.evaluateAnswer1 = __bind(this.evaluateAnswer1, this);
      this.initEvaluation = __bind(this.initEvaluation, this);
      var manifest, sounds;
      manifest = [
        {
          id: 'head',
          src: 'pleca1.png'
        }, {
          id: 'inst',
          src: 'inst.png'
        }, {
          id: 'c1',
          src: 'circle1.png'
        }, {
          id: 'c2',
          src: 'circle2.png'
        }, {
          id: 'n1',
          src: 'nube1.png'
        }, {
          id: 'n2',
          src: 'nube2.png'
        }, {
          id: 'n3',
          src: 'nube3.png'
        }, {
          id: 'table1food4',
          src: 'food_beans.png'
        }, {
          id: 'table3food3',
          src: 'food_brocoli.png'
        }, {
          id: 'table2food1',
          src: 'food_corn.png'
        }, {
          id: 'table1food3',
          src: 'food_eggs.png'
        }, {
          id: 'table3food2',
          src: 'food_fish.png'
        }, {
          id: 'table2food2',
          src: 'food_icecream.png'
        }, {
          id: 'table3food1',
          src: 'food_lettuce.png'
        }, {
          id: 'table1food1',
          src: 'food_milk.png'
        }, {
          id: 'table1food2',
          src: 'food_pancakes.png'
        }, {
          id: 'table2food3',
          src: 'food_peaches.png'
        }, {
          id: 'table2food4',
          src: 'food_spinach.png'
        }, {
          id: 'table3food4',
          src: 'food_tomato.png'
        }, {
          id: 'imageJack',
          src: 'image_Jack.png'
        }, {
          id: 'imageMeg',
          src: 'image_Meg.png'
        }, {
          id: 'imageTomandSue',
          src: 'image_TomandSue.png'
        }, {
          id: 'labelJack',
          src: 'label_Jack.png'
        }, {
          id: 'labelMeg',
          src: 'label_Meg.png'
        }, {
          id: 'labelTomandSue',
          src: 'label_TomandSue.png'
        }, {
          id: 'lineaJack',
          src: 'linea_Jack.png'
        }, {
          id: 'lineaMeg',
          src: 'linea_Meg.png'
        }, {
          id: 'lineaTomandSue',
          src: 'linea_TomandSue.png'
        }, {
          id: 'Table1num1',
          src: 'Table1_1.png'
        }, {
          id: 'Table1num2',
          src: 'Table1_2.png'
        }, {
          id: 'Table1num3',
          src: 'Table1_3.png'
        }, {
          id: 'Table1num4',
          src: 'Table1_4.png'
        }, {
          id: 'Table1num5',
          src: 'Table1_5.png'
        }, {
          id: 'Table1num6',
          src: 'Table1_6.png'
        }, {
          id: 'Table1num7',
          src: 'Table1_7.png'
        }, {
          id: 'Table1num8',
          src: 'Table1_8.png'
        }, {
          id: 'Table1num9',
          src: 'Table1_9.png'
        }, {
          id: 'Table1num10',
          src: 'Table1_10.png'
        }, {
          id: 'Table1num11',
          src: 'Table1_11.png'
        }, {
          id: 'Table1num12',
          src: 'Table1_12.png'
        }, {
          id: 'Table2num1',
          src: 'Table2_1.png'
        }, {
          id: 'Table2num2',
          src: 'Table2_2.png'
        }, {
          id: 'Table2num3',
          src: 'Table2_3.png'
        }, {
          id: 'Table2num4',
          src: 'Table2_4.png'
        }, {
          id: 'Table2num5',
          src: 'Table2_5.png'
        }, {
          id: 'Table2num6',
          src: 'Table2_6.png'
        }, {
          id: 'Table2num7',
          src: 'Table2_7.png'
        }, {
          id: 'Table2num8',
          src: 'Table2_8.png'
        }, {
          id: 'Table2num9',
          src: 'Table2_9.png'
        }, {
          id: 'Table2num10',
          src: 'Table2_10.png'
        }, {
          id: 'Table2num11',
          src: 'Table2_11.png'
        }, {
          id: 'Table2num12',
          src: 'Table2_12.png'
        }, {
          id: 'Table3num1',
          src: 'Table3_1.png'
        }, {
          id: 'Table3num2',
          src: 'Table3_2.png'
        }, {
          id: 'Table3num3',
          src: 'Table3_3.png'
        }, {
          id: 'Table3num4',
          src: 'Table3_4.png'
        }, {
          id: 'Table3num5',
          src: 'Table3_5.png'
        }, {
          id: 'Table3num6',
          src: 'Table3_6.png'
        }, {
          id: 'Table3num7',
          src: 'Table3_7.png'
        }, {
          id: 'Table3num8',
          src: 'Table3_8.png'
        }, {
          id: 'Table3num9',
          src: 'Table3_9.png'
        }, {
          id: 'Table3num10',
          src: 'Table3_10.png'
        }, {
          id: 'Table3num11',
          src: 'Table3_11.png'
        }, {
          id: 'Table3num12',
          src: 'Table3_12.png'
        }
      ];
      sounds = [
        {
          src: 'sounds/boing.mp3',
          id: 'boing'
        }, {
          src: 'sounds/good.mp3',
          id: 'good'
        }, {
          src: 'sounds/TU2_U3_A4_instructions.mp3',
          id: 'instructions'
        }, {
          src: 'sounds/wrong.mp3',
          id: 'wrong'
        }
      ];
      this.answers = [
        {
          a1: 0,
          a2: 3,
          a3: 12
        }, {
          a1: 0,
          a2: 7,
          a3: 11
        }, {
          a1: 0,
          a2: 7,
          a3: 10
        }, {
          a1: 0,
          a2: 7,
          a3: 9
        }, {
          a1: 2,
          a2: 6,
          a3: 12
        }, {
          a1: 2,
          a2: 6,
          a3: 11
        }, {
          a1: 2,
          a2: 6,
          a3: 10
        }, {
          a1: 2,
          a2: 5,
          a3: 9
        }, {
          a1: 1,
          a2: 5,
          a3: 12
        }, {
          a1: 1,
          a2: 8,
          a3: 11
        }, {
          a1: 1,
          a2: 5,
          a3: 10
        }, {
          a1: 1,
          a2: 6,
          a3: 9
        }
      ];
      U3A4.__super__.constructor.call(this, null, manifest, sounds);
    }

    U3A4.prototype.setStage = function() {
      U3A4.__super__.setStage.apply(this, arguments);
      this.insertBitmap('header', 'head', stageSize.w / 2, 0, 'tc');
      this.insertBitmap('instructions', 'inst', 20, 100);
      this.addToMain(new Score('score', this.preload.getResult('c1'), this.preload.getResult('c2'), 20, 500, 12, 0));
      return this.setDropper().setClouds(1).setFaces().setTable(3).introEvaluation();
    };

    U3A4.prototype.setDropper = function() {
      this.addToMain(new WordContainer('dropper1', '', '#FFF', '#F59743', 170, 541, 188, 30));
      this.addToMain(new WordContainer('dropper2', '', '#FFF', '#F59743', 373, 541, 158, 30));
      this.addToMain(new WordContainer('dropper3', '', '#FFF', '#F59743', 544, 541, 136, 30));
      return this;
    };

    U3A4.prototype.setClouds = function() {
      var n1, n2, n3, nube1, nube2, nube3, t1n1, t1n2, t1n3, t2n1, t2n2, t2n3, t3n1, t3n2, t3n3, t4n2, t4n3, t5n2, t6n2;
      nube1 = new createjs.Container();
      nube1.x = 77;
      nube1.y = 388;
      nube1.name = 'nube1';
      nube2 = new createjs.Container();
      nube2.x = 272;
      nube2.y = 369;
      nube2.name = 'nube2';
      nube3 = new createjs.Container();
      nube3.x = 581;
      nube3.y = 372;
      nube3.name = 'nube3';
      n1 = this.createBitmap('n1', 'n1', 0, 0);
      n2 = this.createBitmap('n2', 'n2', 0, 0);
      n3 = this.createBitmap('n3', 'n3', 0, 0);
      t1n1 = new DraggableText('t1n1', "They", 0, 32, 42);
      t2n1 = new DraggableText('t2n1', "He", 1, 80, 74);
      t3n1 = new DraggableText('t3n1', "She", 2, 90, 21);
      t1n2 = new DraggableText('t1n2', "like", 3, 103, 91);
      t2n2 = new DraggableText('t2n2', "don't like", 4, 119, 24);
      t3n2 = new DraggableText('t3n2', "likes", 5, 55, 38);
      t4n2 = new DraggableText('t4n2', "doesn't likes", 6, 134, 62);
      t5n2 = new DraggableText('t5n2', "love", 7, 188, 98);
      t6n2 = new DraggableText('t6n2', "loves", 8, 23, 75);
      t1n3 = new DraggableText('t1n3', "Tomatoes", 9, 32, 23);
      t2n3 = new DraggableText('t2n3', "Broccoli", 10, 92, 48);
      t3n3 = new DraggableText('t3n3', "fish", 11, 23, 67);
      t4n3 = new DraggableText('t4n3', "lettuce", 12, 85, 87);
      nube1.addChild(n1, t1n1, t2n1, t3n1);
      nube2.addChild(n2, t1n2, t2n2, t3n2, t4n2, t5n2, t6n2);
      nube3.addChild(n3, t1n3, t2n3, t3n3, t4n3);
      this.addToLibrary(t1n1, t2n1, t3n1, t1n2, t2n2, t3n2, t4n2, t5n2, t6n2, t1n3, t2n3, t3n3, t4n3);
      this.addToMain(nube1, nube2, nube3);
      return this;
    };

    U3A4.prototype.setFaces = function() {
      this.insertBitmap('lineaJack', 'lineaJack', 178, 257);
      this.insertBitmap('lineaMeg', 'lineaMeg', 137, 200);
      this.insertBitmap('lineaTomandSue', 'lineaTomandSue', 138, 313);
      this.insertBitmap('imageJack', 'imageJack', 164, 186);
      this.insertBitmap('imageMeg', 'imageMeg', 70, 124);
      this.insertBitmap('imageTomandSue', 'imageTomandSue', 1, 240);
      this.insertBitmap('labelJack', 'labelJack', 177, 264);
      this.insertBitmap('labelMeg', 'labelMeg', 95, 186);
      this.insertBitmap('labelTomandSue', 'labelTomandSue', 58, 323);
      return this;
    };

    U3A4.prototype.setTable = function(table) {
      var i, smiley, smileys, _i, _j, _k;
      smileys = new createjs.Container();
      smileys.x = 246;
      smileys.y = 174;
      smileys.name = 'smileys';
      this.insertBitmap("table" + table + "food1", "table" + table + "food1", 298, 171, 'bc');
      this.insertBitmap("table" + table + "food2", "table" + table + "food2", 429, 171, 'bc');
      this.insertBitmap("table" + table + "food3", "table" + table + "food3", 558, 171, 'bc');
      this.insertBitmap("table" + table + "food4", "table" + table + "food4", 690, 171, 'bc');
      for (i = _i = 0; _i <= 3; i = ++_i) {
        smiley = this.createBitmap("Table" + table + "num" + (i + 1), "Table" + table + "num" + (i + 1), i * 130, 0);
        smileys.addChild(smiley);
        this.addToLibrary(smiley);
      }
      for (i = _j = 0; _j <= 3; i = ++_j) {
        smiley = this.createBitmap("Table" + table + "num" + (i + 5), "Table" + table + "num" + (i + 5), i * 130, 58);
        smileys.addChild(smiley);
        this.addToLibrary(smiley);
      }
      for (i = _k = 0; _k <= 3; i = ++_k) {
        smiley = this.createBitmap("Table" + table + "num" + (i + 9), "Table" + table + "num" + (i + 9), i * 130, 116);
        smileys.addChild(smiley);
        this.addToLibrary(smiley);
      }
      this.addToMain(smileys);
      return this;
    };

    U3A4.prototype.introEvaluation = function() {
      var i, _i, _j, _k;
      U3A4.__super__.introEvaluation.apply(this, arguments);
      for (i = _i = 1; _i <= 3; i = _i += 1) {
        this.observer.subscribe('init_evaluation', this.library["t" + i + "n1"].onInitEvaluation);
      }
      for (i = _j = 1; _j <= 6; i = _j += 1) {
        this.observer.subscribe('init_evaluation', this.library["t" + i + "n2"].onInitEvaluation);
      }
      for (i = _k = 1; _k <= 4; i = _k += 1) {
        this.observer.subscribe('init_evaluation', this.library["t" + i + "n3"].onInitEvaluation);
      }
      TweenLite.from(this.library['header'], 1, {
        y: -this.library['header'].height
      });
      TweenLite.from(this.library['instructions'], 1, {
        alpha: 0,
        x: 0,
        delay: 0.5,
        onComplete: this.playInstructions,
        onCompleteParams: [this]
      });
      return TweenMax.allFrom([this.library['nube1'], this.library['nube2'], this.library['nube3']], 1, {
        alpha: 0,
        y: stageSize.h,
        delay: 2
      });
    };

    U3A4.prototype.initEvaluation = function(e) {
      var i, _i, _results;
      U3A4.__super__.initEvaluation.apply(this, arguments);
      _results = [];
      for (i = _i = 1; _i <= 3; i = _i += 1) {
        _results.push(this.library["t" + i + "n1"].addEventListener('drop', this.evaluateAnswer1));
      }
      return _results;

      /*
      		for i in [1..6] by 1
      			@library["t#{i}n2"].addEventListener 'drop', @evaluateAnswer
      		for i in [1..4] by 1
      			@library["t#{i}n3"].addEventListener 'drop', @evaluateAnswer
      */
    };

    U3A4.prototype.evaluateAnswer1 = function(e) {
      var i, pt, _i, _j, _results;
      this.answer = e.target;
      _results = [];
      for (i = _i = 1; _i <= 3; i = _i += 1) {
        pt = this.library["dropper1"].globalToLocal(this.stage.mouseX, this.stage.mouseY);
        if (this.library["dropper1"].hitTest(pt.x, pt.y)) {
          if (this.answer.index === this.answers[this.index].a1) {
            this.answer.x = this.answer.pos.x;
            this.answer.y = this.answer.pos.y;
            this.library['dropper1'].changeText(this.answer.text.text);
            for (i = _j = 1; _j <= 6; i = _j += 1) {
              this.library["t" + i + "n2"].addEventListener('drop', this.evaluateAnswer2);
            }
            _results.push(false);
          } else {
            this.answer.returnToPlace();
            _results.push(this.warning());
          }
        } else {
          _results.push(this.answer.returnToPlace());
        }
      }
      return _results;
    };

    U3A4.prototype.evaluateAnswer2 = function(e) {
      var i, pt, _i, _j, _results;
      this.answer = e.target;
      _results = [];
      for (i = _i = 1; _i <= 6; i = _i += 1) {
        pt = this.library["dropper2"].globalToLocal(this.stage.mouseX, this.stage.mouseY);
        if (this.library["dropper2"].hitTest(pt.x, pt.y)) {
          if (this.answer.index === this.answers[this.index].a2) {
            this.answer.x = this.answer.pos.x;
            this.answer.y = this.answer.pos.y;
            this.library['dropper2'].changeText(this.answer.text.text);
            for (i = _j = 1; _j <= 4; i = _j += 1) {
              this.library["t" + i + "n3"].addEventListener('drop', this.evaluateAnswer3);
            }
            _results.push(false);
          } else {
            this.answer.returnToPlace();
            _results.push(this.warning());
          }
        } else {
          _results.push(this.answer.returnToPlace());
        }
      }
      return _results;
    };

    U3A4.prototype.evaluateAnswer3 = function(e) {
      var i, pt, _i, _results;
      this.answer = e.target;
      _results = [];
      for (i = _i = 1; _i <= 6; i = _i += 1) {
        pt = this.library["dropper3"].globalToLocal(this.stage.mouseX, this.stage.mouseY);
        if (this.library["dropper3"].hitTest(pt.x, pt.y)) {
          if (this.answer.index === this.answers[this.index].a3) {
            this.answer.x = this.answer.pos.x;
            this.answer.y = this.answer.pos.y;
            this.library['dropper3'].changeText(this.answer.text.text);
            _results.push(setTimeout(this.finishEvaluation, 1 * 1000));
          } else {
            this.answer.returnToPlace();
            _results.push(this.warning());
          }
        } else {
          _results.push(this.answer.returnToPlace());
        }
      }
      return _results;
    };

    U3A4.prototype.finishEvaluation = function() {
      this.library['score'].plusOne();
      createjs.Sound.play('good');
      return this.nextEvaluation();
    };

    U3A4.prototype.nextEvaluation = function() {
      this.index++;
      if (this.index < this.answers.length) {
        this.library['dropper1'].changeText('');
        this.library['dropper2'].changeText('');
        return this.library['dropper3'].changeText('');
      } else {
        return this.finish();
      }
    };

    U3A4.prototype.finish = function() {
      return U3A4.__super__.finish.apply(this, arguments);
    };

    window.U3A4 = U3A4;

    return U3A4;

  })(Oda);

}).call(this);
