// Generated by CoffeeScript 1.6.3
(function() {
  var U4A2,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  U4A2 = (function(_super) {
    __extends(U4A2, _super);

    function U4A2() {
      this.repeatSound = __bind(this.repeatSound, this);
      this.nextEvaluation = __bind(this.nextEvaluation, this);
      this.finishEvaluation = __bind(this.finishEvaluation, this);
      this.evaluateAnswer = __bind(this.evaluateAnswer, this);
      this.initDraw = __bind(this.initDraw, this);
      this.initEvaluation = __bind(this.initEvaluation, this);
      var manifest, sounds;
      manifest = [
        {
          id: 'head',
          src: 'pleca1.png'
        }, {
          id: 'inst',
          src: 'inst.png'
        }, {
          id: 'c1',
          src: 'circle1.png'
        }, {
          id: 'c2',
          src: 'circle2.png'
        }, {
          id: 'repeatbtn',
          src: 'repeat-btn.png'
        }, {
          id: 'playagain',
          src: 'play_again.png'
        }, {
          id: 'startgame',
          src: 'start_game.png'
        }, {
          id: 'bluewhale',
          src: 'bluewhale_img.png'
        }, {
          id: 'dolphin',
          src: 'dolphin_img.png'
        }, {
          id: 'eagle',
          src: 'eagle_img.png'
        }, {
          id: 'giantpanda',
          src: 'giantpanda_img.png'
        }, {
          id: 'polarbear',
          src: 'polarbear_img.png'
        }, {
          id: 'gorilla',
          src: 'gorilla_img.png'
        }, {
          id: 'jaguar',
          src: 'jaguar_img.png'
        }, {
          id: 'lion',
          src: 'lion_img.png'
        }, {
          id: 'seaturttle',
          src: 'seaturttle_img.png'
        }
      ];
      sounds = [
        {
          src: 'sounds/boing.mp3',
          id: 'boing'
        }, {
          src: 'sounds/good.mp3',
          id: 'good'
        }, {
          src: 'sounds/TU2_U4_A2_instructions.mp3',
          id: 'instructions'
        }
      ];
      this.letters = [['g', 'i', 'a', 'n', 't', 'p', 'a', 'n', 'd', 'a'], ['p', 's', 'e', 'a', 't', 'u', 'r', 't', 'l', 'e'], ['o', 'u', 's', 'q', 'f', 'a', 't', 'y', 'i', 'j'], ['l', 'g', 'e', 'x', 'k', 'e', 'j', 'd', 'o', 'a'], ['a', 'e', 'd', 'o', 'l', 'p', 'h', 'i', 'n', 'g'], ['r', 'a', 'n', 'h', 'y', 'j', 'i', 'n', 'b', 'u'], ['b', 'g', 'o', 'r', 'i', 'l', 'l', 'a', 't', 'a'], ['e', 'l', 'k', 'd', 'o', 'z', 'p', 'l', 'n', 'r'], ['a', 'e', 'o', 'f', 'e', 'a', 'd', 'o', 'f', 'l'], ['r', 'b', 'l', 'u', 'e', 'w', 'h', 'a', 'l', 'e']];
      this.answers = [];
      U4A2.__super__.constructor.call(this, null, manifest, sounds);
    }

    U4A2.prototype.setStage = function() {
      U4A2.__super__.setStage.apply(this, arguments);
      this.insertBitmap('header', 'head', stageSize.w / 2, 0, 'tc');
      this.insertBitmap('instructions', 'inst', 20, 100);
      this.addToMain(new Score('score', this.preload.getResult('c1'), this.preload.getResult('c2'), 20, 500, 5, 0));
      return this.setAnimals().setSopa().introEvaluation();
    };

    U4A2.prototype.setAnimals = function() {
      this.insertBitmap('bluewhale', 'bluewhale', 509, 465);
      this.insertBitmap('dolphin', 'dolphin', 227, 460);
      this.insertBitmap('eagle', 'eagle', 43, 131);
      this.insertBitmap('giantpanda', 'giantpanda', 661, 249);
      this.insertBitmap('gorilla', 'gorilla', 122, 361);
      this.insertBitmap('jaguar', 'jaguar', 142, 132);
      this.insertBitmap('lion', 'lion', 586, 130);
      this.insertBitmap('seaturttle', 'seaturttle', 590, 372);
      this.insertBitmap('polarbear', 'polarbear', 368, 424);
      return this;
    };

    U4A2.prototype.setSopa = function() {
      var h, i, letra, sopa, _i, _j, _ref, _ref1;
      this.shapeCanvas = new createjs.Shape();
      sopa = new createjs.Container();
      sopa.x = 297;
      sopa.y = 148;
      sopa.name = 'sopa';
      for (h = _i = 0, _ref = this.letters.length - 1; _i <= _ref; h = _i += 1) {
        for (i = _j = 0, _ref1 = this.letters[h].length - 1; _j <= _ref1; i = _j += 1) {
          letra = new ClickableText(this.letters[h][i], this.letters[h][i], 'l#{h+i}', i * 26, h * 26);
          letra.text.font = '20px Arial';
          letra.text.textAlign = 'center';
          sopa.addChild(letra);
        }
      }
      sopa.addChild(this.shapeCanvas);
      this.addToMain(sopa);
      return this;
    };

    U4A2.prototype.introEvaluation = function() {
      U4A2.__super__.introEvaluation.apply(this, arguments);
      TweenLite.from(this.library['header'], 1, {
        y: -this.library['header'].height
      });
      TweenLite.from(this.library['instructions'], 1, {
        alpha: 0,
        x: 0,
        delay: 0.5
      });
      TweenLite.from(this.library['sopa'], 1, {
        alpha: 0,
        y: this.library['sopa'].y - 20,
        delay: 0.5,
        onComplete: this.playInstructions,
        onCompleteParams: [this]
      });
      return TweenMax.allFrom([this.library['bluewhale'], this.library['dolphin'], this.library['eagle'], this.library['giantpanda'], this.library['gorilla'], this.library['jaguar'], this.library['lion'], this.library['seaturttle'], this.library['polarbear']], 1, {
        alpha: 0,
        delay: 1.5
      }, 0.1);
    };

    U4A2.prototype.initEvaluation = function(e) {
      U4A2.__super__.initEvaluation.apply(this, arguments);
      this.shapeCanvas.graphics.s("rgba(255, 0, 0, 1)").f("rgba(255, 0, 0, 0.5)").rr(20, 20, 100, 50, 10);
      return this.mainContainer.addEventListener('mousedown', this.initDraw);
    };

    U4A2.prototype.initDraw = function(e) {
      return console.log(e);
    };

    U4A2.prototype.evaluateAnswer = function(e) {
      var pt;
      this.answer = e.target;
      pt = this.library['dropname'].globalToLocal(this.stage.mouseX, this.stage.mouseY);
      if (this.library['dropname'].hitTest(pt.x, pt.y)) {
        if (this.answer.index === this.answers[this.index].id) {
          this.answer.blink(false);
          return setTimeout(this.finishEvaluation, 1 * 1000);
        } else {
          this.warning();
          return this.answer.returnToPlace();
        }
      } else {
        return this.answer.returnToPlace();
      }
    };

    U4A2.prototype.finishEvaluation = function() {
      TweenLite.to(this.library['characters'], 0.5, {
        alpha: 0,
        y: -200,
        ease: Back.easeOut,
        onComplete: this.nextEvaluation
      });
      return this.answer.returnToPlace();
    };

    U4A2.prototype.nextEvaluation = function() {
      this.index++;
      if (this.index < this.answers.length) {
        this.library['score'].updateCount(this.index);
        this.library['characters'].alpha = 1;
        this.library['characters'].y = stageSize.h - 180;
        this.library['characters'].currentFrame = this.answers[this.index].id;
        createjs.Sound.play(this.answers[this.index].sound);
        return TweenLite.from(this.library['characters'], 0.5, {
          alpha: 0,
          y: this.library['characters'].y + 20,
          ease: Quart.easeOut
        });
      } else {
        return this.finish();
      }
    };

    U4A2.prototype.repeatSound = function() {
      return createjs.Sound.play(this.answers[this.index].sound);
    };

    U4A2.prototype.finish = function() {
      var i, _i, _results;
      U4A2.__super__.finish.apply(this, arguments);
      _results = [];
      for (i = _i = 1; _i <= 6; i = _i += 1) {
        _results.push(this.library['name' + i].blink(false));
      }
      return _results;
    };

    window.U4A2 = U4A2;

    return U4A2;

  })(Oda);

}).call(this);
