// Generated by CoffeeScript 1.6.3
(function() {
  var Draggable, U1A1,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Draggable = (function() {
    function Draggable(name, img, side, sel, x, y) {
      this.name = name;
      this.img = img;
      this.side = side;
      this.sel = sel;
      this.x = x;
      this.y = y;
      this.initialize(name, img, side, sel, x, y);
    }

    return Draggable;

  })();

  U1A1 = (function() {
    function U1A1() {}

    U1A1.prototype.init = function() {
      var preload;
      preload = new createjs.LoadQueue(false);
      preload.addEventListener('complete', this.handleComplete);
      preload.addEventListener('progress', this.handleProgress);
      preload.loadManifest([
        {
          id: 'isb',
          src: imgurl + 'test.jpg'
        }, {
          id: 'isb',
          src: imgurl + 'test1.jpg'
        }
      ]);
      return false;
    };

    U1A1.prototype.handleProgress = function() {
      var percent;
      percent = Math.round(preload.progress * 100);
      $('#preloader').text(percent + '%');
      return false;
    };

    U1A1.prototype.handleComplete = function() {
      $('#preloader').hide();
      initAssets();
      setStage();
      setListeners();
      createjs.Ticker.addListener(window);
      createjs.Ticker.setFPS(60);
      return false;
    };

    return U1A1;

  })();

  $(document).ready(function() {
    var u1a1;
    u1a1 = new U1A1();
    u1a1.init();
    return false;
  });

  window.Test = (function() {
    function Test() {
      this.drawCircle = __bind(this.drawCircle, this);
      this.stage = new createjs.Stage(document.getElementById('canvas'));
      this.circle = {
        x: 10,
        y: 20,
        r: 10
      };
      TweenLite.to(this.circle, 2, {
        delay: 2,
        x: 500,
        y: 20,
        ease: Elastic.easeOut
      });
      createjs.Ticker.addListener(this);
    }

    Test.prototype.drawCircle = function() {
      var circle;
      circle = new createjs.Shape();
      circle.graphics.beginFill('#606').drawCircle(this.circle.x, this.circle.y, this.circle.r);
      return this.stage.addChild(circle);
    };

    Test.prototype.tick = function() {
      this.stage.removeAllChildren();
      this.drawCircle();
      return this.stage.update();
    };

    return Test;

  })();

  window.init = function() {
    return new Test();
  };

}).call(this);
