// Generated by CoffeeScript 1.6.3
(function() {
  var WordContainer;

  WordContainer = (function() {
    function WordContainer(name, text, bgcolor, stcolor, x, y, w, h) {
      if (w == null) {
        w = 100;
      }
      if (h == null) {
        h = 20;
      }
      this.initialize(name, text, bgcolor, stcolor, x, y, w, h);
    }

    WordContainer.prototype = new createjs.Container();

    WordContainer.prototype.Container_initialize = WordContainer.prototype.initialize;

    WordContainer.prototype.initialize = function(name, text, bgcolor, stcolor, x, y, w, h) {
      if (w == null) {
        w = 10;
      }
      if (h == null) {
        h = 20;
      }
      this.Container_initialize();
      this.name = name;
      this.x = x;
      this.y = y;
      this.text = new createjs.Text(text, '24px Arial', '#333');
      this.graphic = new createjs.Graphics().beginFill(bgcolor).drawRect(0, 0, this.text.getMeasuredWidth() + 10, this.text.getMeasuredHeight()).beginStroke(stcolor).moveTo(0, this.text.getMeasuredHeight()).lineTo(this.text.getMeasuredWidth() + 10, this.text.getMeasuredHeight());
      this.shape = new createjs.Shape(this.graphic);
      this.w = this.text.getMeasuredWidth();
      this.text.x = w / 2;
      this.addChild(this.shape);
      return false;
    };

    WordContainer.prototype.changeText = function(text) {
      this.text.text = text;
      return this.text.textAlign = 'center';
    };

    WordContainer.prototype.blink = function(state) {
      if (state == null) {
        state = true;
      }
      TweenMax.killTweensOf(this);
      this.alpha = 1;
      if (state) {
        return TweenMax.to(this, 0.2, {
          alpha: .2,
          repeat: -1,
          yoyo: true
        });
      }
    };

    window.WordContainer = WordContainer;

    return WordContainer;

  })();

}).call(this);
