// Generated by CoffeeScript 1.6.3
(function() {
  var U3A1,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  U3A1 = (function(_super) {
    __extends(U3A1, _super);

    function U3A1() {
      this.repeatSound = __bind(this.repeatSound, this);
      this.nextEvaluation = __bind(this.nextEvaluation, this);
      this.finishEvaluation = __bind(this.finishEvaluation, this);
      this.evaluateAnswer = __bind(this.evaluateAnswer, this);
      this.initEvaluation = __bind(this.initEvaluation, this);
      var manifest, sounds;
      manifest = [
        {
          id: 'head',
          src: 'pleca.png'
        }, {
          id: 'inst',
          src: 'texto_look.png'
        }, {
          id: 'c1',
          src: 'circle1.png'
        }, {
          id: 'c2',
          src: 'circle2.png'
        }, {
          id: 'repeatbtn',
          src: 'repeat-btn.png'
        }, {
          id: 'guia1',
          src: 'guia1.png'
        }, {
          id: 'guia1b',
          src: 'guia1b.png'
        }, {
          id: 'guia2',
          src: 'guia2.png'
        }, {
          id: 'guia2b',
          src: 'guia2b.png'
        }, {
          id: 'guia3',
          src: 'guia3.png'
        }, {
          id: 'guia3b',
          src: 'guia3b.png'
        }, {
          id: 'hojabreakfast',
          src: 'hoja_breakfast.png'
        }, {
          id: 'hojadinner',
          src: 'hoja_dinner.png'
        }, {
          id: 'hojalunch',
          src: 'hoja_lunch.png'
        }, {
          id: 'labelbreakfast',
          src: 'label_breakfast.png'
        }, {
          id: 'labeldinner',
          src: 'label_dinner.png'
        }, {
          id: 'labellunch',
          src: 'label_lunch.png'
        }, {
          id: 'menuback',
          src: 'menuback.png'
        }, {
          id: 'menubreakfast',
          src: 'menu_breakfast.png'
        }, {
          id: 'menudinner',
          src: 'menu_dinner.png'
        }, {
          id: 'menulunch',
          src: 'menu_lunch.png'
        }, {
          id: 'bigm1c1',
          src: 'bigm1c1.png'
        }, {
          id: 'bigm1c2',
          src: 'bigm1c2.png'
        }, {
          id: 'bigm1c3',
          src: 'bigm1c3.png'
        }, {
          id: 'bigm1c4',
          src: 'bigm1c4.png'
        }, {
          id: 'bigm1c5',
          src: 'bigm1c5.png'
        }, {
          id: 'bigm1c6',
          src: 'bigm1c6.png'
        }, {
          id: 'bigm1c7',
          src: 'bigm1c7.png'
        }, {
          id: 'bigm1c8',
          src: 'bigm1c8.png'
        }, {
          id: 'bigm1c9',
          src: 'bigm1c9.png'
        }, {
          id: 'm1c1',
          src: 'm1c1.png'
        }, {
          id: 'm1c2',
          src: 'm1c2.png'
        }, {
          id: 'm1c3',
          src: 'm1c3.png'
        }, {
          id: 'm1c4',
          src: 'm1c4.png'
        }, {
          id: 'm1c5',
          src: 'm1c5.png'
        }, {
          id: 'm1c6',
          src: 'm1c6.png'
        }, {
          id: 'm1c7',
          src: 'm1c7.png'
        }, {
          id: 'm1c8',
          src: 'm1c8.png'
        }, {
          id: 'm1c9',
          src: 'm1c9.png'
        }, {
          id: 'm1c10',
          src: 'm1c10.png'
        }, {
          id: 'm1c11',
          src: 'm1c11.png'
        }, {
          id: 'm1c12',
          src: 'm1c12.png'
        }, {
          id: 'm1c13',
          src: 'm1c13.png'
        }, {
          id: 'm1c14',
          src: 'm1c14.png'
        }, {
          id: 'bigm2c1',
          src: 'bigm2c1.png'
        }, {
          id: 'bigm2c2',
          src: 'bigm2c2.png'
        }, {
          id: 'bigm2c3',
          src: 'bigm2c3.png'
        }, {
          id: 'bigm2c4',
          src: 'bigm2c4.png'
        }, {
          id: 'bigm2c5',
          src: 'bigm2c5.png'
        }, {
          id: 'bigm2c6',
          src: 'bigm2c6.png'
        }, {
          id: 'bigm2c7',
          src: 'bigm2c7.png'
        }, {
          id: 'bigm2c8',
          src: 'bigm2c8.png'
        }, {
          id: 'bigm2c9',
          src: 'bigm2c9.png'
        }, {
          id: 'm2c1',
          src: 'm2c1.png'
        }, {
          id: 'm2c2',
          src: 'm2c2.png'
        }, {
          id: 'm2c3',
          src: 'm2c3.png'
        }, {
          id: 'm2c4',
          src: 'm2c4.png'
        }, {
          id: 'm2c5',
          src: 'm2c5.png'
        }, {
          id: 'm2c6',
          src: 'm2c6.png'
        }, {
          id: 'm2c7',
          src: 'm2c7.png'
        }, {
          id: 'm2c8',
          src: 'm2c8.png'
        }, {
          id: 'm2c9',
          src: 'm2c9.png'
        }, {
          id: 'm2c10',
          src: 'm2c10.png'
        }, {
          id: 'm2c11',
          src: 'm2c11.png'
        }, {
          id: 'm2c12',
          src: 'm2c12.png'
        }, {
          id: 'm2c13',
          src: 'm2c13.png'
        }, {
          id: 'm2c14',
          src: 'm2c14.png'
        }, {
          id: 'bigm3c1',
          src: 'bigm3c1.png'
        }, {
          id: 'bigm3c2',
          src: 'bigm3c2.png'
        }, {
          id: 'bigm3c3',
          src: 'bigm3c3.png'
        }, {
          id: 'bigm3c4',
          src: 'bigm3c4.png'
        }, {
          id: 'bigm3c5',
          src: 'bigm3c5.png'
        }, {
          id: 'bigm3c6',
          src: 'bigm3c6.png'
        }, {
          id: 'bigm3c7',
          src: 'bigm3c7.png'
        }, {
          id: 'bigm3c8',
          src: 'bigm3c8.png'
        }, {
          id: 'bigm3c9',
          src: 'bigm3c9.png'
        }, {
          id: 'm3c1',
          src: 'm3c1.png'
        }, {
          id: 'm3c2',
          src: 'm3c2.png'
        }, {
          id: 'm3c3',
          src: 'm3c3.png'
        }, {
          id: 'm3c4',
          src: 'm3c4.png'
        }, {
          id: 'm3c5',
          src: 'm3c5.png'
        }, {
          id: 'm3c6',
          src: 'm3c6.png'
        }, {
          id: 'm3c7',
          src: 'm3c7.png'
        }, {
          id: 'm3c8',
          src: 'm3c8.png'
        }, {
          id: 'm3c9',
          src: 'm3c9.png'
        }, {
          id: 'm3c10',
          src: 'm3c10.png'
        }, {
          id: 'm3c11',
          src: 'm3c11.png'
        }, {
          id: 'm3c12',
          src: 'm3c12.png'
        }, {
          id: 'm3c13',
          src: 'm3c13.png'
        }, {
          id: 'm3c14',
          src: 'm3c14.png'
        }, {
          id: 'bigm4c1',
          src: 'bigm4c1.png'
        }, {
          id: 'bigm4c2',
          src: 'bigm4c2.png'
        }, {
          id: 'bigm4c3',
          src: 'bigm4c3.png'
        }, {
          id: 'bigm4c4',
          src: 'bigm4c4.png'
        }, {
          id: 'bigm4c5',
          src: 'bigm4c5.png'
        }, {
          id: 'bigm4c6',
          src: 'bigm4c6.png'
        }, {
          id: 'bigm4c7',
          src: 'bigm4c7.png'
        }, {
          id: 'bigm4c8',
          src: 'bigm4c8.png'
        }, {
          id: 'bigm4c9',
          src: 'bigm4c9.png'
        }, {
          id: 'm4c1',
          src: 'm4c1.png'
        }, {
          id: 'm4c2',
          src: 'm4c2.png'
        }, {
          id: 'm4c3',
          src: 'm4c3.png'
        }, {
          id: 'm4c4',
          src: 'm4c4.png'
        }, {
          id: 'm4c5',
          src: 'm4c5.png'
        }, {
          id: 'm4c6',
          src: 'm4c6.png'
        }, {
          id: 'm4c7',
          src: 'm4c7.png'
        }, {
          id: 'm4c8',
          src: 'm4c8.png'
        }, {
          id: 'm4c9',
          src: 'm4c9.png'
        }, {
          id: 'm4c10',
          src: 'm4c10.png'
        }, {
          id: 'm4c11',
          src: 'm4c11.png'
        }, {
          id: 'm4c12',
          src: 'm4c12.png'
        }, {
          id: 'm4c13',
          src: 'm4c13.png'
        }, {
          id: 'm4c14',
          src: 'm4c14.png'
        }
      ];
      sounds = [
        {
          src: 'sounds/boing.mp3',
          id: 'boing'
        }, {
          src: 'sounds/TU2_U3_A1_instructions.mp3',
          id: 'instructions'
        }
      ];
      this.answers = [];
      this.menu1 = {
        arriba: [
          {
            id: 'bigm1c1',
            x: '185',
            y: '202'
          }, {
            id: 'bigm1c2',
            x: '261',
            y: '202'
          }, {
            id: 'bigm1c3',
            x: '181',
            y: '296'
          }, {
            id: 'bigm1c4',
            x: '352',
            y: '168'
          }, {
            id: 'bigm1c5',
            x: '372',
            y: '234'
          }, {
            id: 'bigm1c6',
            x: '362',
            y: '320'
          }, {
            id: 'bigm1c7',
            x: '534',
            y: '179'
          }, {
            id: 'bigm1c8',
            x: '530',
            y: '254'
          }, {
            id: 'bigm1c9',
            x: '590',
            y: '275'
          }
        ],
        abajo: [
          {
            id: 'm1c1',
            x: '143',
            y: '473'
          }, {
            id: 'm1c2',
            x: '206',
            y: '454'
          }, {
            id: 'm1c3',
            x: '260',
            y: '455'
          }, {
            id: 'm1c4',
            x: '322',
            y: '459'
          }, {
            id: 'm1c5',
            x: '417',
            y: '455'
          }, {
            id: 'm1c6',
            x: '489',
            y: '452'
          }, {
            id: 'm1c7',
            x: '586',
            y: '461'
          }, {
            id: 'm1c8',
            x: '690',
            y: '474'
          }, {
            id: 'm1c9',
            x: '182',
            y: '526'
          }, {
            id: 'm1c10',
            x: '284',
            y: '515'
          }, {
            id: 'm1c11',
            x: '364',
            y: '527'
          }, {
            id: 'm1c12',
            x: '448',
            y: '522'
          }, {
            id: 'm1c13',
            x: '536',
            y: '519'
          }, {
            id: 'm1c14',
            x: '609',
            y: '536'
          }
        ]
      };
      this.menu2 = {
        arriba: [
          {
            id: 'bigm2c1',
            x: '181',
            y: '163'
          }, {
            id: 'bigm2c2',
            x: '259',
            y: '232'
          }, {
            id: 'bigm2c3',
            x: '184',
            y: '279'
          }, {
            id: 'bigm2c4',
            x: '353',
            y: '177'
          }, {
            id: 'bigm2c5',
            x: '408',
            y: '274'
          }, {
            id: 'bigm2c6',
            x: '339',
            y: '279'
          }, {
            id: 'bigm2c7',
            x: '548',
            y: '177'
          }, {
            id: 'bigm2c8',
            x: '554',
            y: '245'
          }, {
            id: 'bigm2c9',
            x: '536',
            y: '308'
          }
        ],
        abajo: [
          {
            id: 'm2c1',
            x: '145',
            y: '466'
          }, {
            id: 'm2c2',
            x: '235',
            y: '473'
          }, {
            id: 'm2c3',
            x: '292',
            y: '460'
          }, {
            id: 'm2c4',
            x: '373',
            y: '473'
          }, {
            id: 'm2c5',
            x: '462',
            y: '458'
          }, {
            id: 'm2c6',
            x: '523',
            y: '466'
          }, {
            id: 'm2c7',
            x: '615',
            y: '469'
          }, {
            id: 'm2c8',
            x: '664',
            y: '458'
          }, {
            id: 'm2c9',
            x: '207',
            y: '525'
          }, {
            id: 'm2c10',
            x: '298',
            y: '525'
          }, {
            id: 'm2c11',
            x: '380',
            y: '517'
          }, {
            id: 'm2c12',
            x: '491',
            y: '518'
          }, {
            id: 'm2c13',
            x: '557',
            y: '532'
          }, {
            id: 'm2c14',
            x: '635',
            y: '515'
          }
        ]
      };
      this.menu3 = {
        arriba: [
          {
            id: 'bigm3c1',
            x: '189',
            y: '177'
          }, {
            id: 'bigm3c2',
            x: '262',
            y: '217'
          }, {
            id: 'bigm3c3',
            x: '186',
            y: '303'
          }, {
            id: 'bigm3c4',
            x: '364',
            y: '174'
          }, {
            id: 'bigm3c5',
            x: '353',
            y: '251'
          }, {
            id: 'bigm3c6',
            x: '403',
            y: '272'
          }, {
            id: 'bigm3c7',
            x: '534',
            y: '174'
          }, {
            id: 'bigm3c8',
            x: '587',
            y: '249'
          }, {
            id: 'bigm3c9',
            x: '537',
            y: '315'
          }
        ],
        abajo: [
          {
            id: 'm3c1',
            x: '152',
            y: '451'
          }, {
            id: 'm3c2',
            x: '207',
            y: '447'
          }, {
            id: 'm3c3',
            x: '254',
            y: '449'
          }, {
            id: 'm3c4',
            x: '319',
            y: '460'
          }, {
            id: 'm3c5',
            x: '403',
            y: '453'
          }, {
            id: 'm3c6',
            x: '462',
            y: '456'
          }, {
            id: 'm3c7',
            x: '530',
            y: '458'
          }, {
            id: 'm3c8',
            x: '628',
            y: '449'
          }, {
            id: 'm3c9',
            x: '175',
            y: '521'
          }, {
            id: 'm3c10',
            x: '251',
            y: '504'
          }, {
            id: 'm3c11',
            x: '339',
            y: '519'
          }, {
            id: 'm3c12',
            x: '434',
            y: '526'
          }, {
            id: 'm3c13',
            x: '516',
            y: '519'
          }, {
            id: 'm3c14',
            x: '623',
            y: '526'
          }
        ]
      };
      this.menu4 = {
        arriba: [
          {
            id: 'bigm4c1',
            x: '184',
            y: '191'
          }, {
            id: 'bigm4c2',
            x: '262',
            y: '227'
          }, {
            id: 'bigm4c3',
            x: '192',
            y: '287'
          }, {
            id: 'bigm4c4',
            x: '351',
            y: '181'
          }, {
            id: 'bigm4c5',
            x: '445',
            y: '235'
          }, {
            id: 'bigm4c6',
            x: '355',
            y: '309'
          }, {
            id: 'bigm4c7',
            x: '535',
            y: '174'
          }, {
            id: 'bigm4c8',
            x: '560',
            y: '241'
          }, {
            id: 'bigm4c9',
            x: '535',
            y: '313'
          }
        ],
        abajo: [
          {
            id: 'm4c1',
            x: '136',
            y: '453'
          }, {
            id: 'm4c2',
            x: '192',
            y: '469'
          }, {
            id: 'm4c3',
            x: '272',
            y: '454'
          }, {
            id: 'm4c4',
            x: '325',
            y: '463'
          }, {
            id: 'm4c5',
            x: '413',
            y: '462'
          }, {
            id: 'm4c6',
            x: '519',
            y: '454'
          }, {
            id: 'm4c7',
            x: '580',
            y: '474'
          }, {
            id: 'm4c8',
            x: '654',
            y: '462'
          }, {
            id: 'm4c9',
            x: '166',
            y: '523'
          }, {
            id: 'm4c10',
            x: '264',
            y: '526'
          }, {
            id: 'm4c11',
            x: '351',
            y: '522'
          }, {
            id: 'm4c12',
            x: '452',
            y: '527'
          }, {
            id: 'm4c13',
            x: '538',
            y: '519'
          }, {
            id: 'm4c14',
            x: '623',
            y: '525'
          }
        ]
      };
      this.menu = [
        {
          id: 'menuback',
          x: '157',
          y: '121'
        }, {
          id: 'hojabreakfast',
          x: '164',
          y: '132'
        }, {
          id: 'hojadinner',
          x: '510',
          y: '127'
        }, {
          id: 'hojalunch',
          x: '337',
          y: '132'
        }, {
          id: 'menubreakfast',
          x: '174',
          y: '164'
        }, {
          id: 'menudinner',
          x: '526',
          y: '161'
        }, {
          id: 'menulunch',
          x: '349',
          y: '164'
        }, {
          id: 'labelbreakfast',
          x: '214',
          y: '149'
        }, {
          id: 'labeldinner',
          x: '582',
          y: '150'
        }, {
          id: 'labellunch',
          x: '407',
          y: '151'
        }
      ];
      U3A1.__super__.constructor.call(this, null, manifest, sounds);
    }

    U3A1.prototype.setStage = function() {
      U3A1.__super__.setStage.apply(this, arguments);
      this.insertBitmap('header', 'head', stageSize.w / 2, 0, 'tc');
      this.insertBitmap('instructions', 'inst', 20, 100);
      this.addToMain(new Score('score', this.preload.getResult('c1'), this.preload.getResult('c2'), 20, 500, 5, 0));
      return this.setDropper().setMenu1().introEvaluation();
    };

    U3A1.prototype.setDropper = function() {
      var h1, myname, question;
      myname = new createjs.Container();
      myname.x = 285;
      myname.y = stageSize.h - 70;
      myname.name = 'dropname';
      question = this.createBitmap('question', 'q', 0, 0);
      h1 = new Droppable('h1', '#FFFFFF', 250, 0, 120, 22);
      myname.addChild(question, h1);
      this.addToLibrary(h1);
      this.addToMain(myname);
      return this;
    };

    U3A1.prototype.setMenu1 = function() {
      var i, menu, menu1, menu2, menu3, menu4, repeat, v, _i, _j, _k, _l, _m, _n, _o, _p, _q;
      menu = new createjs.Container();
      menu.x = 0;
      menu.y = 0;
      menu1 = new createjs.Container();
      menu1.x = 0;
      menu1.y = 0;
      menu2 = new createjs.Container();
      menu2.x = 0;
      menu2.y = 0;
      menu3 = new createjs.Container();
      menu3.x = 0;
      menu3.y = 0;
      menu4 = new createjs.Container();
      menu4.x = 0;
      menu4.y = 0;
      this.insertBitmap('repeatbtn', 'repeatbtn', 404, 413);
      repeat = new Button('btnrepeat', this.preload.getResult('repeat'), 0, 300, 320);
      for (i = _i = 1; _i <= 10; i = ++_i) {
        v = this.createBitmap(this.menu[i - 1].id, this.menu[i - 1].id, this.menu[i - 1].x, this.menu[i - 1].y);
        menu.addChild(v);
        this.addToLibrary(v);
      }
      for (i = _j = 1; _j <= 14; i = ++_j) {
        v = new Draggable('m1c' + i, this.preload.getResult('m1c' + i), i, this.menu1.abajo[i - 1].x, this.menu1.abajo[i - 1].y);
        menu1.addChild(v);
        this.addToLibrary(v);
      }
      for (i = _k = 1; _k <= 9; i = ++_k) {
        v = this.createBitmap('bigm1c' + i, 'bigm1c' + i, this.menu1.arriba[i - 1].x, this.menu1.arriba[i - 1].y);
        menu1.addChild(v);
        this.addToLibrary(v);
      }
      for (i = _l = 1; _l <= 14; i = ++_l) {
        v = new Draggable('m2c' + i, this.preload.getResult('m2c' + i), i, this.menu2.abajo[i - 1].x, this.menu2.abajo[i - 1].y);
        menu2.addChild(v);
        this.addToLibrary(v);
      }
      for (i = _m = 1; _m <= 9; i = ++_m) {
        v = this.createBitmap('bigm2c' + i, 'bigm2c' + i, this.menu2.arriba[i - 1].x, this.menu2.arriba[i - 1].y);
        menu2.addChild(v);
        this.addToLibrary(v);
      }
      for (i = _n = 1; _n <= 14; i = ++_n) {
        v = new Draggable('m3c' + i, this.preload.getResult('m3c' + i), i, this.menu3.abajo[i - 1].x, this.menu3.abajo[i - 1].y);
        menu3.addChild(v);
        this.addToLibrary(v);
      }
      for (i = _o = 1; _o <= 9; i = ++_o) {
        v = this.createBitmap('bigm3c' + i, 'bigm3c' + i, this.menu3.arriba[i - 1].x, this.menu3.arriba[i - 1].y);
        menu3.addChild(v);
        this.addToLibrary(v);
      }
      for (i = _p = 1; _p <= 14; i = ++_p) {
        v = new Draggable('m4c' + i, this.preload.getResult('m4c' + i), i, this.menu4.abajo[i - 1].x, this.menu4.abajo[i - 1].y);
        menu4.addChild(v);
        this.addToLibrary(v);
      }
      for (i = _q = 1; _q <= 9; i = ++_q) {
        v = this.createBitmap('bigm4c' + i, 'bigm4c' + i, this.menu4.arriba[i - 1].x, this.menu4.arriba[i - 1].y);
        menu4.addChild(v);
        this.addToLibrary(v);
      }
      repeat.addEventListener('click', this.repeatSound);
      menu1.addChild(repeat);
      this.addToMain(menu);
      this.addToMain(menu1);
      /*@addToMain menu2
      		@addToMain menu3
      		@addToMain menu4
      */

      return this;
    };

    U3A1.prototype.introEvaluation = function() {
      return U3A1.__super__.introEvaluation.apply(this, arguments);
      /*
      		for i in [1..6] by 1
      			@observer.subscribe 'init_evaluation', @library['name'+i].onInitEvaluation
      
      		@library['characters'].currentFrame = @answers[@index].id
      
      		TweenLite.from @library['header'], 1, {y:-@library['header'].height}
      		TweenLite.from @library['instructions'], 1, {alpha :0, x: 0, delay: 0.5}
      		TweenLite.from @library['names'], 1, {alpha: 0, y: @library['names'].y + 50, delay: 1}
      		TweenLite.from @library['dropname'], 1, {alpha: 0, y: @library['dropname'].y + 50, delay: 1}
      		TweenLite.from @library['characters'], 1, {alpha: 0, y: @library['characters'].y + 20, delay: 1.5, onComplete: @playInstructions, onCompleteParams: [@]}
      */

    };

    U3A1.prototype.initEvaluation = function(e) {
      U3A1.__super__.initEvaluation.apply(this, arguments);
      this.library['characters'].currentFrame = this.answers[this.index].id;
      createjs.Sound.play(this.answers[this.index].sound);
      return TweenLite.to(this.library['characters'], 0.5, {
        alpha: 1,
        y: stageSize.h - 180,
        ease: Quart.easeOut
      });
    };

    U3A1.prototype.evaluateAnswer = function(e) {
      var pt;
      this.answer = e.target;
      pt = this.library['dropname'].globalToLocal(this.stage.mouseX, this.stage.mouseY);
      if (this.library['dropname'].hitTest(pt.x, pt.y)) {
        if (this.answer.index === this.answers[this.index].id) {
          this.answer.blink(false);
          return setTimeout(this.finishEvaluation, 1 * 1000);
        } else {
          this.warning();
          return this.answer.returnToPlace();
        }
      } else {
        return this.answer.returnToPlace();
      }
    };

    U3A1.prototype.finishEvaluation = function() {
      TweenLite.to(this.library['characters'], 0.5, {
        alpha: 0,
        y: -200,
        ease: Back.easeOut,
        onComplete: this.nextEvaluation
      });
      return this.answer.returnToPlace();
    };

    U3A1.prototype.nextEvaluation = function() {
      this.index++;
      if (this.index < this.answers.length) {
        this.library['score'].updateCount(this.index);
        this.library['characters'].alpha = 1;
        this.library['characters'].y = stageSize.h - 180;
        this.library['characters'].currentFrame = this.answers[this.index].id;
        createjs.Sound.play(this.answers[this.index].sound);
        return TweenLite.from(this.library['characters'], 0.5, {
          alpha: 0,
          y: this.library['characters'].y + 20,
          ease: Quart.easeOut
        });
      } else {
        return this.finish();
      }
    };

    U3A1.prototype.repeatSound = function() {
      return createjs.Sound.play(this.answers[this.index].sound);
    };

    U3A1.prototype.finish = function() {
      var i, _i, _results;
      U3A1.__super__.finish.apply(this, arguments);
      _results = [];
      for (i = _i = 1; _i <= 6; i = _i += 1) {
        _results.push(this.library['name' + i].blink(false));
      }
      return _results;
    };

    window.U3A1 = U3A1;

    return U3A1;

  })(Oda);

}).call(this);
