// Generated by CoffeeScript 1.6.3
(function() {
  var U6A3,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  U6A3 = (function(_super) {
    __extends(U6A3, _super);

    function U6A3() {
      this.nextEvaluation = __bind(this.nextEvaluation, this);
      this.clearEvaluation = __bind(this.clearEvaluation, this);
      this.finishEvaluation = __bind(this.finishEvaluation, this);
      this.evaluateAnswer3 = __bind(this.evaluateAnswer3, this);
      this.evaluateAnswer2 = __bind(this.evaluateAnswer2, this);
      this.evaluateAnswer1 = __bind(this.evaluateAnswer1, this);
      this.initEvaluation = __bind(this.initEvaluation, this);
      var manifest, sounds;
      manifest = [
        {
          id: 'head',
          src: 'pleca.png'
        }, {
          id: 'inst',
          src: 'texto_look.png'
        }, {
          id: 'c1',
          src: 'circle1.png'
        }, {
          id: 'c2',
          src: 'circle2.png'
        }, {
          id: 'aBank',
          src: 'a-bank.png'
        }, {
          id: 'aBusstop',
          src: 'a-bus-stop.png'
        }, {
          id: 'aCandystore',
          src: 'a-candy-store.png'
        }, {
          id: 'aGasstation',
          src: 'a-gas-station.png'
        }, {
          id: 'aGrocerystore',
          src: 'a-grocery-store.png'
        }, {
          id: 'aHospital',
          src: 'a-hospital.png'
        }, {
          id: 'aLibrary',
          src: 'a-library.png'
        }, {
          id: 'aMovietheater',
          src: 'a-movie-theater.png'
        }, {
          id: 'aPetstore',
          src: 'a-pet-store.png'
        }, {
          id: 'aPolicestation',
          src: 'a-police-station.png'
        }, {
          id: 'aPostoffice',
          src: 'a-post-office.png'
        }, {
          id: 'aRestaurant',
          src: 'a-restaurant.png'
        }, {
          id: 'aShoestore',
          src: 'a-shoe-store.png'
        }, {
          id: 'anAnimalhospital',
          src: 'an-animal-hospital.png'
        }, {
          id: 'anInternetcafe',
          src: 'an-Internet-cafe.png'
        }, {
          id: 'n1',
          src: 'tag_preposition.png'
        }, {
          id: 'n2',
          src: 'tag_words.png'
        }
      ];
      sounds = [
        {
          src: 'sounds/boing.mp3',
          id: 'boing'
        }, {
          src: 'sounds/good.mp3',
          id: 'good'
        }, {
          src: 'sounds/wrong.mp3',
          id: 'wrong'
        }, {
          src: 'sounds/TU2_U4_A6_Instructions.mp3',
          id: 'instructions'
        }
      ];
      this.info = [
        {
          img: 'cafe',
          frase: ''
        }, {
          img: 'stop',
          frase: 'I need to take a bus.'
        }, {
          img: 'library',
          frase: ''
        }, {
          img: 'grocery',
          frase: 'I need some groceries.'
        }, {
          img: 'police',
          frase: 'I have a problem! I need some help!'
        }, {
          img: 'candy',
          frase: 'I want a box of chocolates.'
        }, {
          img: 'post',
          frase: 'I need to send a postcard.'
        }, {
          img: 'animal',
          frase: ''
        }, {
          img: 'bus',
          frase: ''
        }, {
          img: 'theater',
          frase: 'I want to watch a movie.'
        }, {
          img: 'pet',
          frase: 'I need some dog food.'
        }, {
          img: 'shoe',
          frase: 'I need some sandals.'
        }, {
          img: 'gas',
          frase: 'I need some gas.'
        }, {
          img: 'station',
          frase: ''
        }, {
          img: 'store',
          frase: ''
        }, {
          img: 'hospital',
          frase: ''
        }, {
          img: 'bank',
          frase: ''
        }, {
          img: 'internet',
          frase: 'I need to send an e-mail.'
        }, {
          img: 'movie',
          frase: ''
        }, {
          img: 'office',
          frase: ''
        }
      ];
      U6A3.__super__.constructor.call(this, null, manifest, sounds);
    }

    U6A3.prototype.setStage = function() {
      var Imgs;
      U6A3.__super__.setStage.apply(this, arguments);
      this.insertBitmap('header', 'head', stageSize.w / 2, 0, 'tc');
      this.insertBitmap('instructions', 'inst', 20, 100);
      Imgs = this.createSprite('images', ['aBank', 'aBusstop', 'aCandystore', 'aGasstation', 'aGrocerystore', 'aHospital', 'aLibrary', 'aMovietheater', 'aPetstore', 'aPolicestation', 'aPostoffice', 'aRestaurant', 'aShoestore', 'anAnimalhospital', 'anInternetcafe'], null, stageSize.w / 2, 215, 'mc');
      Imgs.scaleX = Imgs.scaleY = 0.3;
      this.addToMain(Imgs);
      this.addToMain(new Score('score', this.preload.getResult('c1'), this.preload.getResult('c2'), 20, 500, 5, 0));
      return this.setDropper().setNube1().setNube2().introEvaluation();
    };

    U6A3.prototype.setDropper = function() {
      var dropper, frase, h1, h2, h3, isThere, question;
      dropper = new createjs.Container();
      dropper.x = stageSize.w / 2 - 160;
      dropper.y = this.library['images'].y + 10;
      dropper.name = 'dropper';
      frase = new createjs.Text(this.info[1].frase, '24px Arial', '#333');
      frase.x = 160;
      frase.y = 110;
      frase.textAlign = 'center';
      dropper.addChild(frase);
      isThere = new createjs.Text('Is there', '24px Arial', '#333');
      isThere.x = 0;
      isThere.y = 140;
      dropper.addChild(isThere);
      h1 = new WordContainer('h1', '', '', '#f00', 90, 145, 40, 22);
      h2 = new WordContainer('h2', '', '', '#f00', 140, 145, 90, 22);
      h3 = new WordContainer('h3', '', '', '#f00', 240, 145, 55, 22);
      question = new createjs.Text('?', '24px Arial', '#333');
      question.x = 300;
      question.y = 140;
      dropper.addChild(question);
      dropper.addChild(h1, h2, h3);
      this.addToLibrary(h1, h2, h3);
      this.addToMain(dropper);
      return this;
    };

    U6A3.prototype.setNube1 = function() {
      var back, container, p1n1, p2n1;
      container = new createjs.Container();
      container.x = 100;
      container.y = this.library['dropper'].y + 180;
      container.name = 'nube1';
      back = this.createBitmap('backNube1', 'n1', 0, 0);
      p1n1 = new DraggableText('p1n1', "a", 0, 26, 15);
      p2n1 = new DraggableText('p2n1', "an", 1, 44, 30);
      container.addChild(back, p1n1, p2n1);
      this.addToLibrary(back, p1n1, p2n1);
      this.addToMain(container);
      return this;
    };

    U6A3.prototype.setNube2 = function() {
      var back, container, p10n2, p11n2, p12n2, p13n2, p14n2, p15n2, p16n2, p17n2, p18n2, p19n2, p1n2, p20n2, p2n2, p3n2, p4n2, p5n2, p6n2, p7n2, p8n2, p9n2;
      container = new createjs.Container();
      container.x = 250;
      container.y = this.library['dropper'].y + 180;
      container.name = 'nube2';
      back = this.createBitmap('backNube2', 'n2', 0, 0);
      p1n2 = new DraggableText('p1n2', "cafe", 0, 20, 25);
      p2n2 = new DraggableText('p2n2', "stop", 1, 24, 70);
      p3n2 = new DraggableText('p3n2', "library", 2, 65, 45);
      p4n2 = new DraggableText('p4n2', "grocery", 3, 74, 85);
      p5n2 = new DraggableText('p5n2', "police", 4, 56, 107);
      p6n2 = new DraggableText('p6n2', "candy", 5, 124, 26);
      p7n2 = new DraggableText('p7n2', "post", 6, 141, 60);
      p8n2 = new DraggableText('p8n2', "animal", 7, 152, 105);
      p9n2 = new DraggableText('p9n2', "bus", 8, 200, 21);
      p10n2 = new DraggableText('p10n2', "theater", 9, 189, 66);
      p11n2 = new DraggableText('p11n2', "pet", 10, 253, 33);
      p12n2 = new DraggableText('p12n2', "shoe", 11, 240, 100);
      p13n2 = new DraggableText('p13n2', "gas", 12, 303, 25);
      p14n2 = new DraggableText('p14n2', "station", 13, 273, 71);
      p15n2 = new DraggableText('p15n2', "store", 14, 327, 46);
      p16n2 = new DraggableText('p16n2', "hospital", 15, 305, 104);
      p17n2 = new DraggableText('p17n2', "bank", 16, 378, 25);
      p18n2 = new DraggableText('p18n2', "internet", 17, 363, 75);
      p19n2 = new DraggableText('p19n2', "movie", 18, 383, 111);
      p20n2 = new DraggableText('p20n2', "office", 19, 418, 48);
      container.addChild(back, p1n2, p2n2, p3n2, p4n2, p5n2, p6n2, p7n2, p8n2, p9n2, p10n2, p11n2, p12n2, p13n2, p14n2, p15n2, p16n2, p17n2, p18n2, p19n2, p20n2);
      this.addToLibrary(back, p1n2, p2n2, p3n2, p4n2, p5n2, p6n2, p7n2, p8n2, p9n2, p10n2, p11n2, p12n2, p13n2, p14n2, p15n2, p16n2, p17n2, p18n2, p19n2, p20n2);
      this.addToMain(container);
      return this;
    };

    U6A3.prototype.introEvaluation = function() {
      var i, _i, _j, _k;
      U6A3.__super__.introEvaluation.apply(this, arguments);
      for (i = _i = 1; _i <= 2; i = _i += 1) {
        this.observer.subscribe('init_evaluation', this.library['p' + i + 'n1'].onInitEvaluation);
      }
      for (i = _j = 1; _j <= 4; i = _j += 1) {
        this.observer.subscribe('init_evaluation', this.library['p' + i + 'n2'].onInitEvaluation);
      }
      for (i = _k = 1; _k <= 5; i = _k += 1) {
        this.observer.subscribe('init_evaluation', this.library['p' + i + 'n3'].onInitEvaluation);
      }
      this.library['characters'].currentFrame = this.index;
      this.library['characters'].scaleX = 1;
      this.library['characters'].scaleY = 1;
      this.library['characters'].alpha = 1;
      TweenLite.from(this.library['header'], 1, {
        y: -this.library['header'].height
      });
      TweenLite.from(this.library['instructions'], 1, {
        alpha: 0,
        x: 0,
        delay: 0.5
      });
      TweenLite.from(this.library['characters'], 1, {
        alpha: 0,
        y: this.library['characters'].y + 50,
        delay: 1
      });
      TweenLite.from(this.library['dropper'], 1, {
        alpha: 0,
        y: this.library['dropper'].y + 20,
        delay: 1.2
      });
      TweenLite.from(this.library['nube1'], 1, {
        alpha: 0,
        y: this.library['nube1'].y + 20,
        delay: 1.4
      });
      TweenLite.from(this.library['nube2'], 1, {
        alpha: 0,
        y: this.library['nube2'].y + 20,
        delay: 1.5
      });
      return TweenLite.from(this.library['nube3'], 1, {
        alpha: 0,
        y: this.library['nube3'].y + 20,
        delay: 1.6,
        onComplete: this.playInstructions,
        onCompleteParams: [this]
      });
    };

    U6A3.prototype.initEvaluation = function(e) {
      var i, _i;
      U6A3.__super__.initEvaluation.apply(this, arguments);
      this.library['h1'].blink();
      this.blink(this.library['backNube1']);
      for (i = _i = 1; _i <= 2; i = _i += 1) {
        this.library['p' + i + 'n1'].addEventListener('drop', this.evaluateAnswer1);
      }
      return false;
    };

    U6A3.prototype.evaluateAnswer1 = function(e) {
      var i, pt, _i;
      this.answer = e.target;
      pt = this.library['h1'].globalToLocal(this.stage.mouseX, this.stage.mouseY);
      if (this.library['h1'].hitTest(pt.x, pt.y)) {
        if (this.answer.index === this.answers[this.index].w1) {
          this.answer.visible = false;
          this.library['h1'].changeText(this.answer.text.text);
          this.library['h1'].blink(false);
          this.blink(this.library['backNube1'], false);
          this.library['h2'].blink();
          this.blink(this.library['backNube2']);
          for (i = _i = 1; _i <= 4; i = _i += 1) {
            this.library['p' + i + 'n2'].addEventListener('drop', this.evaluateAnswer2);
          }
          return false;
        } else {
          this.warning();
          return this.answer.returnToPlace();
        }
      } else {
        return this.answer.returnToPlace();
      }
    };

    U6A3.prototype.evaluateAnswer2 = function(e) {
      var i, pt, _i, _results;
      this.answer = e.target;
      pt = this.library['h2'].globalToLocal(this.stage.mouseX, this.stage.mouseY);
      if (this.library['h2'].hitTest(pt.x, pt.y)) {
        if (this.answer.index === this.answers[this.index].w2) {
          this.answer.visible = false;
          this.library['h2'].changeText(this.answer.text.text);
          this.library['h2'].blink(false);
          this.blink(this.library['backNube2'], false);
          this.library['h3'].blink();
          this.blink(this.library['backNube3']);
          _results = [];
          for (i = _i = 1; _i <= 5; i = _i += 1) {
            _results.push(this.library['p' + i + 'n3'].addEventListener('drop', this.evaluateAnswer3));
          }
          return _results;
        } else {
          this.warning();
          return this.answer.returnToPlace();
        }
      } else {
        return this.answer.returnToPlace();
      }
    };

    U6A3.prototype.evaluateAnswer3 = function(e) {
      var pt;
      this.answer = e.target;
      pt = this.library['h3'].globalToLocal(this.stage.mouseX, this.stage.mouseY);
      if (this.library['h3'].hitTest(pt.x, pt.y)) {
        if (this.answer.index === this.answers[this.index].w3) {
          this.answer.visible = false;
          this.library['h3'].changeText(this.answer.text.text);
          this.library['h3'].blink(false);
          this.blink(this.library['backNube3'], false);
          return setTimeout(this.finishEvaluation, 1 * 1000);
        } else {
          this.warning();
          return this.answer.returnToPlace();
        }
      } else {
        return this.answer.returnToPlace();
      }
    };

    U6A3.prototype.finishEvaluation = function() {
      var song;
      this.library['score'].plusOne();
      song = createjs.Sound.play(this.answers[this.index].sound);
      return song.addEventListener('complete', this.clearEvaluation);
    };

    U6A3.prototype.clearEvaluation = function(e) {
      var i, _i, _j, _k, _l;
      for (i = _i = 1; _i <= 2; i = _i += 1) {
        this.library['p' + i + 'n1'].visible = true;
        this.library['p' + i + 'n1'].returnToPlace();
      }
      for (i = _j = 1; _j <= 4; i = _j += 1) {
        this.library['p' + i + 'n2'].visible = true;
        this.library['p' + i + 'n2'].returnToPlace();
      }
      for (i = _k = 1; _k <= 5; i = _k += 1) {
        this.library['p' + i + 'n3'].visible = true;
        this.library['p' + i + 'n3'].returnToPlace();
      }
      for (i = _l = 1; _l <= 3; i = _l += 1) {
        this.library['h' + i].changeText('');
      }
      return TweenLite.to(this.library['characters'], 0.5, {
        scaleX: 1.5,
        scaleY: 1.5,
        alpha: 0,
        ease: Back.easeOut,
        onComplete: this.nextEvaluation
      });
    };

    U6A3.prototype.nextEvaluation = function() {
      var i, _i, _results;
      this.index++;
      if (this.index < this.answers.length) {
        this.library['characters'].currentFrame = this.index;
        this.library['h1'].blink();
        this.blink(this.library['backNube1']);
        TweenLite.to(this.library['characters'], 0.5, {
          scaleX: 1,
          scaleY: 1,
          alpha: 1,
          ease: Back.easeOut
        });
        _results = [];
        for (i = _i = 1; _i <= 2; i = _i += 1) {
          _results.push(this.library['p' + i + 'n1'].addEventListener('drop', this.evaluateAnswer1));
        }
        return _results;
      } else {
        return this.finish();
      }
    };

    U6A3.prototype.blink = function(obj, state) {
      if (state == null) {
        state = true;
      }
      TweenMax.killTweensOf(obj);
      obj.alpha = 1;
      if (state) {
        return TweenMax.to(obj, 0.5, {
          alpha: .5,
          repeat: -1,
          yoyo: true
        });
      }
    };

    U6A3.prototype.finish = function() {
      return U6A3.__super__.finish.apply(this, arguments);
    };

    window.U6A3 = U6A3;

    return U6A3;

  })(Oda);

}).call(this);
