// Generated by CoffeeScript 1.6.3
(function() {
  var U5A2,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  U5A2 = (function(_super) {
    __extends(U5A2, _super);

    function U5A2() {
      var manifest, sounds;
      manifest = [
        {
          id: 'head',
          src: 'pleca1.png'
        }, {
          id: 'c1',
          src: 'circle1.png'
        }, {
          id: 'c2',
          src: 'circle2.png'
        }, {
          id: 'repeatbtn',
          src: 'repeat-btn.png'
        }, {
          id: 'playagain',
          src: 'play_again.png'
        }, {
          id: 'startgame',
          src: 'start_game.png'
        }, {
          id: 'btn4',
          src: 'btn_Chad.png'
        }, {
          id: 'btn3',
          src: 'btn_Ben.png'
        }, {
          id: 'btn2',
          src: 'btn_Lindsay.png'
        }, {
          id: 'btn1',
          src: 'btn_Matt.png'
        }, {
          id: 'bubbletext',
          src: 'bubble_text.png'
        }, {
          id: 'propback',
          src: 'prop_back.png'
        }
      ];
      sounds = [
        {
          src: 'sounds/good.mp3',
          id: 'good'
        }, {
          src: 'sounds/TU3_U4_A5_instructions.mp3',
          id: 'instructions'
        }, {
          src: 'sounds/wrong.mp3',
          id: 'wrong'
        }
      ];
      U5A2.__super__.constructor.call(this, null, manifest, sounds);
    }

    U5A2.prototype.setStage = function() {
      U5A2.__super__.setStage.apply(this, arguments);
      this.insertBitmap('propback', 'propback', 0, 0);
      this.insertBitmap('header', 'head', stageSize.w / 2, 0, 'tc');
      this.insertInstructions('instructions', 'Read the speech bubbles and click on the corresponding character.', 40, 100);
      this.addToMain(new Score('score', this.preload.getResult('c1'), this.preload.getResult('c2'), 20, 500, 15, 0));
      return this.setFaces().introEvaluation();
    };

    U5A2.prototype.setFaces = function() {
      var b, c, faces, i, t, _i;
      faces = new createjs.Container();
      faces.x = 446;
      faces.y = 443;
      b = this.createBitmap('bubbletext', 'bubbletext', 0, 0);
      t = new ClickableText('t', 'Ben is deaf, so they’re speaking in sign language. ', 1, 10, 5);
      t.textAlign = 'center';
      faces.addChild(b, t);
      for (i = _i = 1; _i <= 4; i = ++_i) {
        c = this.createBitmap("btn" + i, "btn" + i, (i - 1) * 80, 50);
        faces.addChild(c);
      }
      this.addToMain(faces);
      return this;
    };

    U5A2.prototype.introEvaluation = function() {
      U5A2.__super__.introEvaluation.apply(this, arguments);
      TweenLite.from(this.library.header, 1, {
        y: -this.library['header'].height
      });
      return TweenLite.from(this.library.instructions, 1, {
        alpha: 0,
        x: 0,
        delay: 0.5,
        onComplete: this.playInstructions,
        onCompleteParams: [this]
      });
    };

    window.U5A2 = U5A2;

    return U5A2;

  })(Oda);

}).call(this);
