// Generated by CoffeeScript 1.6.3
(function() {
  var U1A5,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  U1A5 = (function(_super) {
    __extends(U1A5, _super);

    function U1A5() {
      this.repeatSound = __bind(this.repeatSound, this);
      this.nextEvaluation = __bind(this.nextEvaluation, this);
      this.finishEvaluation = __bind(this.finishEvaluation, this);
      this.evaluateAnswer = __bind(this.evaluateAnswer, this);
      this.initEvaluation = __bind(this.initEvaluation, this);
      var manifest, sounds;
      manifest = [
        {
          id: 'head',
          src: 'pleca.png'
        }, {
          id: 'inst',
          src: 'texto_look.png'
        }, {
          id: 'c1',
          src: 'circle1.png'
        }, {
          id: 'c2',
          src: 'circle2.png'
        }, {
          id: 'repeatbtn',
          src: 'repeat-btn.png'
        }, {
          id: 'playagain',
          src: 'play_again.png'
        }, {
          id: 'startgame',
          src: 'start_game.png'
        }, {
          id: 'bg',
          src: 'bg.png'
        }
      ];
      sounds = [
        {
          src: 'sounds/boing.mp3',
          id: 'boing'
        }, {
          src: 'sounds/TU2_U4_A6_instructions.mp3',
          id: 'instructions'
        }
      ];
      this.answers = [];
      this.textos = {
        positions: [
          {
            x: '68',
            y: '182'
          }, {
            x: '68',
            y: '251'
          }, {
            x: '68',
            y: '288'
          }, {
            x: '68',
            y: '310'
          }, {
            x: '68',
            y: '346'
          }, {
            x: '68',
            y: '400'
          }, {
            x: '410',
            y: '182'
          }, {
            x: '410',
            y: '201'
          }, {
            x: '410',
            y: '221'
          }, {
            x: '410',
            y: '285'
          }, {
            x: '410',
            y: '322'
          }, {
            x: '410',
            y: '390'
          }
        ],
        parrafo1: ['Two heavy          at the end of the hallway open', 'suddenly. The dining room is full of light. There is a long', '         with big, soft chairs around it. There are some', 'trees growing in the room, there is a waterfall.'],
        parrafo2: ['The air is full of delicious smells--roasted turkey, soup,', 'vegetables, homemade bread and cherry pie.'],
        parrafo3: ["Paul's               growls. He's hungry!"],
        parrafo4: ['The king sits at the end of the table and invites the', 'children to sit down next to him.'],
        parrafo5: ['A golden             in the middle of the table starts to flow.', 'Musicians with          enter the room and start to play', 'a beautiful tune.'],
        parrafo6: ['Servants serve the food to the king and the children.', 'Paul takes a drink from his       .'],
        parrafo7: ['The clear liquid is cool and sweet.'],
        parrafo8: ['"It' + 's delicious!" he says.'],
        parrafo9: ["It's the water that collects in the flowers at night", 'says the king, "it tastes sweet, just like the           ! The', 'unicorns and dragons help us collect the water from the', 'flowers."'],
        parrafo10: ['Megan remembers Amedrah, the purple dragon. "Is there', 'a way for us to get back home?" she asks the king.'],
        parrafo11: ['"Yes, of course. You can leave at any time. Just close your', '        and imagine that Amedrah is flying here. But', 'you and Paul are here for a good reason. You have an', 'important               to ask me!"'],
        parrafo12: ['Megan looks at Paul. How does the king know? Megan', 'says, "You' + "'re right- Our town, Lakeville, is in            .", 'We need your help."'],
        drags: [
          {
            id: 'doors',
            x: '701',
            y: '492'
          }, {
            id: 'table',
            x: '665',
            y: '547'
          }, {
            id: 'stomach*',
            x: '731',
            y: '532'
          }, {
            id: 'fountain',
            x: '557',
            y: '497'
          }, {
            id: 'flutes',
            x: '496',
            y: '484'
          }, {
            id: 'cup',
            x: '595',
            y: '542'
          }, {
            id: 'flowers',
            x: '574',
            y: '459'
          }, {
            id: 'eyes',
            x: '659',
            y: '468'
          }, {
            id: 'question',
            x: '518',
            y: '533'
          }, {
            id: 'trouble',
            x: '634',
            y: '511'
          }
        ]
      };
      U1A5.__super__.constructor.call(this, null, manifest, sounds);
    }

    U1A5.prototype.setStage = function() {
      U1A5.__super__.setStage.apply(this, arguments);
      this.insertBitmap('bg', 'bg', 0, 54);
      this.insertBitmap('header', 'head', stageSize.w / 2, 0, 'tc');
      this.insertBitmap('instructions', 'inst', 20, 100);
      this.addToMain(new Score('score', this.preload.getResult('c1'), this.preload.getResult('c2'), 20, 500, 5, 0));
      return this.setCuento().setDropper().introEvaluation();
    };

    U1A5.prototype.setCuento = function() {
      var i, j, text, _i, _j, _k, _ref;
      text = new createjs.Text('Episode 2', '13px Arial', '#333');
      text.x = 641;
      text.y = 146;
      this.addToMain(text);
      for (i = _i = 1; _i <= 12; i = _i += 1) {
        for (j = _j = 0, _ref = this.textos["parrafo" + i].length; 0 <= _ref ? _j <= _ref : _j >= _ref; j = 0 <= _ref ? ++_j : --_j) {
          text = new createjs.Text(this.textos["parrafo" + i][j], '13px Arial', '#333');
          text.x = this.textos.positions[i - 1].x;
          text.y = this.textos.positions[i - 1].y - (-j * 15);
          this.addToMain(text);
        }
      }
      for (i = _k = 1; _k <= 10; i = ++_k) {
        text = new DraggableText(this.textos.drags[i - 1].id, this.textos.drags[i - 1].id, i, this.textos.drags[i - 1].x, this.textos.drags[i - 1].y);
        this.addToMain(text);
      }
      return this;
    };

    U1A5.prototype.setDropper = function() {
      var dropper, h1, h2, h3, h4, h5, h6, h7, h8, h9;
      dropper = new createjs.Container();
      dropper.x = 0;
      dropper.y = 0;
      dropper.name = 'dropper';
      h1 = new WordContainer('h1', '', '', '#f39234', 130, 184, 35, 13);
      h2 = new WordContainer('h2', '', '', '#f39234', 69, 213, 33, 13);
      h3 = new WordContainer('h3', '', '', '#f39234', 105, 290, 55, 13);
      h4 = new WordContainer('h4', '', '', '#f39234', 122, 348, 47, 13);
      h5 = new WordContainer('h5', '', '', '#f39234', 156, 364, 35, 13);
      h6 = new WordContainer('h6', '', '', '#f39234', 664, 238, 42, 13);
      h7 = new WordContainer('h7', '', '', '#f39234', 409, 339, 30, 13);
      h8 = new WordContainer('h8', '', '', '#f39234', 467, 369, 52, 13);
      h9 = new WordContainer('h9', '', '', '#f39234', 667, 408, 45, 13);
      dropper.addChild(h1, h2, h3, h4, h5, h6, h7, h8, h9);
      this.addToLibrary(h1, h2, h3, h4, h5, h6, h7, h8, h9);
      this.addToMain(dropper);
      return this;
    };

    U1A5.prototype.introEvaluation = function() {
      return U1A5.__super__.introEvaluation.apply(this, arguments);
      /*
      		for i in [1..6] by 1
      			@observer.subscribe 'init_evaluation', @library['name'+i].onInitEvaluation
      
      		@library['characters'].currentFrame = @answers[@index].id
      
      		TweenLite.from @library['header'], 1, {y:-@library['header'].height}
      		TweenLite.from @library['instructions'], 1, {alpha :0, x: 0, delay: 0.5}
      		TweenLite.from @library['names'], 1, {alpha: 0, y: @library['names'].y + 50, delay: 1}
      		TweenLite.from @library['dropname'], 1, {alpha: 0, y: @library['dropname'].y + 50, delay: 1}
      		TweenLite.from @library['characters'], 1, {alpha: 0, y: @library['characters'].y + 20, delay: 1.5, onComplete: @playInstructions, onCompleteParams: [@]}
      */

    };

    U1A5.prototype.initEvaluation = function(e) {
      U1A5.__super__.initEvaluation.apply(this, arguments);
      this.library['characters'].currentFrame = this.answers[this.index].id;
      createjs.Sound.play(this.answers[this.index].sound);
      return TweenLite.to(this.library['characters'], 0.5, {
        alpha: 1,
        y: stageSize.h - 180,
        ease: Quart.easeOut
      });
    };

    U1A5.prototype.evaluateAnswer = function(e) {
      var pt;
      this.answer = e.target;
      pt = this.library['dropname'].globalToLocal(this.stage.mouseX, this.stage.mouseY);
      if (this.library['dropname'].hitTest(pt.x, pt.y)) {
        if (this.answer.index === this.answers[this.index].id) {
          this.answer.blink(false);
          return setTimeout(this.finishEvaluation, 1 * 1000);
        } else {
          this.warning();
          return this.answer.returnToPlace();
        }
      } else {
        return this.answer.returnToPlace();
      }
    };

    U1A5.prototype.finishEvaluation = function() {
      TweenLite.to(this.library['characters'], 0.5, {
        alpha: 0,
        y: -200,
        ease: Back.easeOut,
        onComplete: this.nextEvaluation
      });
      return this.answer.returnToPlace();
    };

    U1A5.prototype.nextEvaluation = function() {
      this.index++;
      if (this.index < this.answers.length) {
        this.library['score'].updateCount(this.index);
        this.library['characters'].alpha = 1;
        this.library['characters'].y = stageSize.h - 180;
        this.library['characters'].currentFrame = this.answers[this.index].id;
        createjs.Sound.play(this.answers[this.index].sound);
        return TweenLite.from(this.library['characters'], 0.5, {
          alpha: 0,
          y: this.library['characters'].y + 20,
          ease: Quart.easeOut
        });
      } else {
        return this.finish();
      }
    };

    U1A5.prototype.repeatSound = function() {
      return createjs.Sound.play(this.answers[this.index].sound);
    };

    U1A5.prototype.finish = function() {
      var i, _i, _results;
      U1A5.__super__.finish.apply(this, arguments);
      _results = [];
      for (i = _i = 1; _i <= 6; i = _i += 1) {
        _results.push(this.library['name' + i].blink(false));
      }
      return _results;
    };

    window.U1A5 = U1A5;

    return U1A5;

  })(Oda);

}).call(this);
